#!/usr/bin/env node
// Generated by claude-sf-toolkit. Customize for your project.
"use strict";

/**
 * backlog-search.js — Search and filter backlog items (GitHub Issues).
 *
 * Usage:
 *   node scripts/backlog-search.js --repo owner/repo [filters...] [options]
 *
 * Filters (AND logic):
 *   category:X       Filter by category
 *   tag:X            Filter by tag
 *   status:X         Filter by status
 *   priority:X       Filter by priority
 *   assigned:X       Filter by assignee (partial match)
 *   blocked          Show only blocked items
 *   needs-design     Show items tagged needs-design without a design doc
 *   "free text"      Search title, description, and notes
 *
 * Options:
 *   --repo <owner/repo>     GitHub repo (required)
 *   --backend <github>      Data backend (optional; 'github' is the only supported backend)
 *   --json                  Output results as JSON
 *   --count                 Output only the count of matching items
 *   --help                  Show this help message
 */

const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");

const REPO_ROOT = path.join(__dirname, "..");

// ---------------------------------------------------------------------------
// Argument parsing
// ---------------------------------------------------------------------------

const rawArgs = process.argv.slice(2);

// Check for --help
if (rawArgs.includes("--help")) {
  console.log(
    [
      "Usage: node scripts/backlog-search.js --repo owner/repo [filters...] [options]",
      "",
      "Filters (AND logic):",
      "  category:X       Filter by category",
      "  tag:X            Filter by tag",
      "  status:X         Filter by status",
      "  priority:X       Filter by priority",
      "  assigned:X       Filter by assignee (partial match)",
      "  blocked          Show only blocked items",
      "  needs-design     Show items tagged needs-design without a design doc",
      '  "free text"      Search title, description, and notes',
      "",
      "Options:",
      "  --repo <owner/repo>     GitHub repo (required)",
      "  --backend <github>      Data backend (optional; 'github' is the only supported backend)",
      "  --json                  Output results as JSON",
      "  --count                 Output only the count of matching items",
      "  --help                  Show this help message"
    ].join("\n")
  );
  process.exit(0);
}

// Extract named options
const jsonMode = rawArgs.includes("--json");
const countMode = rawArgs.includes("--count");

let backend = "github";
let repo = null;

const filters = [];
for (let i = 0; i < rawArgs.length; i++) {
  if (rawArgs[i] === "--json" || rawArgs[i] === "--count") continue;
  if (rawArgs[i] === "--backend") {
    backend = (rawArgs[++i] || "").toLowerCase();
    continue;
  }
  if (rawArgs[i] === "--repo") {
    repo = rawArgs[++i];
    continue;
  }
  filters.push(rawArgs[i]);
}

if (backend !== "github") {
  console.error(
    `Error: --backend must be 'github' (got: ${backend}). GitHub Issues is the only supported backend as of v2.0.0.`
  );
  process.exit(1);
}
if (!repo) {
  console.error("Error: --repo <owner/repo> is required");
  process.exit(1);
}

if (filters.length === 0) {
  console.error(
    "Usage: backlog-search.js --repo owner/repo [filters...] [--json] [--count]"
  );
  console.error(
    'Filters: category:X  tag:X  status:X  priority:X  assigned:X  blocked  needs-design  "free text"'
  );
  process.exit(1);
}

// ---------------------------------------------------------------------------
// Category slug → display map (so GitHub-slugged categories like "UI-UX"
// round-trip back to their configured display form like "UI/UX").
// ---------------------------------------------------------------------------

function loadConfiguredCategories() {
  const configPath = path.resolve(REPO_ROOT, "config/sf-toolkit.json");
  try {
    const config = JSON.parse(fs.readFileSync(configPath, "utf8"));
    if (
      config.backlog &&
      Array.isArray(config.backlog.categories) &&
      config.backlog.categories.length > 0
    ) {
      return config.backlog.categories;
    }
  } catch {
    // Config missing or invalid
  }
  return [];
}

function buildCategorySlugMap(categories) {
  const map = {};
  for (const cat of categories) {
    map[cat.replace(/\//g, "-").toLowerCase()] = cat;
  }
  return map;
}

function unslugCategory(rawValue, slugMap) {
  if (!rawValue) return "";
  return slugMap[rawValue.toLowerCase()] || rawValue;
}

// ---------------------------------------------------------------------------
// GitHub Issues source
// ---------------------------------------------------------------------------

const STATUS_LABEL_MAP_GH = {
  captured: "Captured",
  groomed: "Evaluated",
  evaluated: "Evaluated",
  prioritized: "Prioritized",
  ready: "Ready",
  "in-progress": "In Progress",
  "in progress": "In Progress",
  done: "Done",
  deferred: "Deferred"
};

function fetchGitHubIssues(repoArg) {
  try {
    execSync("gh --version", { stdio: "ignore" });
  } catch {
    console.error("Error: 'gh' CLI not found. Install from https://cli.github.com/");
    process.exit(1);
  }
  try {
    const json = execSync(
      `gh issue list --repo ${repoArg} --state all --json number,title,body,state,labels,assignees,createdAt,updatedAt --limit 200`,
      { encoding: "utf8", maxBuffer: 10 * 1024 * 1024 }
    );
    return JSON.parse(json);
  } catch (err) {
    console.error(`Error fetching issues from ${repoArg}: ${err.message}`);
    process.exit(1);
  }
}

function issueToItem(issue, slugMap) {
  const labelNames = (issue.labels || []).map((l) => l.name);
  const statusLabel = labelNames.find((n) => /^status:/i.test(n));
  const status = statusLabel
    ? STATUS_LABEL_MAP_GH[statusLabel.slice("status:".length).toLowerCase()] ||
      "Captured"
    : issue.state === "CLOSED"
      ? "Done"
      : "Captured";
  const priority = labelNames.find((n) => /^P[1-4]$/.test(n)) || "Unset";
  const rawCat = (labelNames.find((n) => /^cat:/i.test(n)) || "").slice(4);
  const effortLabel = labelNames.find((n) => /^effort:/i.test(n));
  const tags = labelNames.filter(
    (n) =>
      !/^(status:|cat:|effort:|complexity:|cbc:|source:|archived$)/i.test(n) &&
      !/^P[1-4]$/.test(n)
  );
  return {
    id: `#${issue.number}`,
    title: issue.title,
    description: issue.body || "",
    category: unslugCategory(rawCat, slugMap),
    status,
    priority,
    effort: effortLabel ? effortLabel.slice("effort:".length) : "Unset",
    tags,
    design_doc: null,
    blocked_by: [],
    devops_wis: [],
    assigned_to:
      (issue.assignees && issue.assignees[0] && issue.assignees[0].login) ||
      null,
    notes: []
  };
}

// Load items
const configuredCategories = loadConfiguredCategories();
const slugMap = buildCategorySlugMap(configuredCategories);
const issues = fetchGitHubIssues(repo);
const items = issues.map((i) => issueToItem(i, slugMap));

// Build filter functions (AND logic)
const predicates = [];

for (const filter of filters) {
  const colonIdx = filter.indexOf(":");
  if (colonIdx > 0) {
    const key = filter.slice(0, colonIdx).toLowerCase();
    const val = filter.slice(colonIdx + 1);

    switch (key) {
      case "category":
        predicates.push(
          (i) => i.category && i.category.toLowerCase() === val.toLowerCase()
        );
        break;
      case "tag":
        // Match both bare legacy labels ("lwc") and prefixed labels ("tag:lwc")
        predicates.push(
          (i) =>
            Array.isArray(i.tags) &&
            i.tags.some(
              (t) =>
                t.toLowerCase() === val.toLowerCase() ||
                t.toLowerCase() === `tag:${val.toLowerCase()}`
            )
        );
        break;
      case "status":
        predicates.push(
          (i) => i.status && i.status.toLowerCase() === val.toLowerCase()
        );
        break;
      case "priority":
        predicates.push(
          (i) => i.priority && i.priority.toLowerCase() === val.toLowerCase()
        );
        break;
      case "assigned":
        predicates.push((i) => {
          const assignee = i.assigned_to || "";
          return assignee.toLowerCase().includes(val.toLowerCase());
        });
        break;
      default:
        // Treat unknown key:val as free text
        predicates.push(makeFreeTextPredicate(filter));
        break;
    }
  } else if (filter === "blocked") {
    predicates.push(
      (i) => Array.isArray(i.blocked_by) && i.blocked_by.length > 0
    );
  } else if (filter === "needs-design") {
    predicates.push(
      (i) =>
        Array.isArray(i.tags) &&
        i.tags.includes("needs-design") &&
        (i.design_doc == null || i.design_doc === "")
    );
  } else {
    // Free text search
    predicates.push(makeFreeTextPredicate(filter));
  }
}

function makeFreeTextPredicate(query) {
  const q = query.toLowerCase();
  return (item) => {
    // Search title
    if (item.title && item.title.toLowerCase().includes(q)) return true;
    // Search description
    if (item.description && item.description.toLowerCase().includes(q))
      return true;
    // Search notes text
    if (Array.isArray(item.notes)) {
      for (const note of item.notes) {
        if (!note) continue;
        const text = typeof note === "string" ? note : note.text || "";
        if (text.toLowerCase().includes(q)) return true;
      }
    }
    return false;
  };
}

// Apply all filters (AND)
const results = items.filter((item) => predicates.every((p) => p(item)));

// Output
if (countMode) {
  console.log(results.length);
} else if (jsonMode) {
  console.log(JSON.stringify(results, null, 2));
} else {
  // Markdown table
  if (results.length === 0) {
    console.log("No matching items found.");
    process.exit(0);
  }

  console.log("| ID | Title | Category | Status | Priority | Effort | Tags |");
  console.log("|---|---|---|---|---|---|---|");
  for (const item of results) {
    const tags = Array.isArray(item.tags) ? item.tags.join(", ") : "";
    const title = (item.title || "").replace(/\|/g, "\\|");
    console.log(
      `| ${item.id} | ${title} | ${item.category} | ${item.status} | ${item.priority} | ${item.effort} | ${tags} |`
    );
  }
  console.log(`\n${results.length} item(s) found.`);
}
