// Generated by claude-sf-toolkit. Customize for your project.
#!/usr/bin/env node
"use strict";

/**
 * backlog-stats.js — Generate statistics from backlog.yaml OR GitHub Issues.
 *
 * Usage:
 *   node scripts/backlog-stats.js [options]
 *
 * Options:
 *   --backend <yaml|github> Data backend (default: yaml)
 *   --repo <owner/repo>     GitHub repo (required when --backend github)
 *   --backlog-path <path>   Path to backlog.yaml (default: docs/backlog/backlog.yaml)
 *   --archive-path <path>   Path to archive.yaml (default: docs/backlog/archive.yaml)
 *   --table                 Human-readable table output (default: JSON)
 *   --help                  Show this help message
 */

const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");
const yaml = require("js-yaml");

const REPO_ROOT = path.join(__dirname, "..");

// ---------------------------------------------------------------------------
// Argument parsing
// ---------------------------------------------------------------------------

function parseCliArgs(argv) {
  const args = {};
  let i = 2;
  while (i < argv.length) {
    const key = argv[i];
    if (key === "--help") {
      console.log(
        [
          "Usage: node scripts/backlog-stats.js [options]",
          "",
          "Options:",
          "  --backend <yaml|github> Data backend (default: yaml)",
          "  --repo <owner/repo>     GitHub repo (required when --backend github)",
          "  --backlog-path <path>   Path to backlog.yaml (default: docs/backlog/backlog.yaml)",
          "  --archive-path <path>   Path to archive.yaml (default: docs/backlog/archive.yaml)",
          "  --table                 Human-readable table output (default: JSON)",
          "  --help                  Show this help message"
        ].join("\n")
      );
      process.exit(0);
    }
    if (key === "--table") {
      args.table = true;
      i++;
    } else if (key.startsWith("--")) {
      const name = key.slice(2);
      if (i + 1 >= argv.length) {
        console.error(`Error: --${name} requires a value`);
        process.exit(1);
      }
      args[name] = argv[i + 1];
      i += 2;
    } else {
      // Positional arg treated as backlog path
      args["backlog-path"] = argv[i];
      i++;
    }
  }
  return args;
}

const CLI_ARGS = parseCliArgs(process.argv);
const tableMode = CLI_ARGS.table || false;
const BACKEND = (CLI_ARGS["backend"] || "yaml").toLowerCase();
const REPO = CLI_ARGS["repo"] || null;

if (BACKEND !== "yaml" && BACKEND !== "github") {
  console.error(`Error: --backend must be 'yaml' or 'github' (got: ${BACKEND})`);
  process.exit(1);
}
if (BACKEND === "github" && !REPO) {
  console.error("Error: --backend github requires --repo <owner/repo>");
  process.exit(1);
}

const BACKLOG_FILE = path.resolve(
  REPO_ROOT,
  CLI_ARGS["backlog-path"] || "docs/backlog/backlog.yaml"
);
const ARCHIVE_FILE = path.resolve(
  REPO_ROOT,
  CLI_ARGS["archive-path"] || "docs/backlog/archive.yaml"
);

// ---------------------------------------------------------------------------
// GitHub Issues source — maps issues into the internal item shape so the
// downstream bucketing logic works unchanged.
// ---------------------------------------------------------------------------

const STATUS_LABEL_MAP = {
  captured: "Captured",
  groomed: "Evaluated",
  evaluated: "Evaluated",
  prioritized: "Prioritized",
  ready: "Ready",
  "in-progress": "In Progress",
  "in progress": "In Progress",
  done: "Done",
  deferred: "Deferred"
};

function loadConfiguredCategories() {
  const configPath = path.resolve(REPO_ROOT, "config/sf-toolkit.json");
  try {
    const config = JSON.parse(fs.readFileSync(configPath, "utf8"));
    if (
      config.backlog &&
      Array.isArray(config.backlog.categories) &&
      config.backlog.categories.length > 0
    ) {
      return config.backlog.categories;
    }
  } catch {
    // Config missing or invalid
  }
  return [];
}

// GitHub labels can't contain "/", so "UI/UX" becomes "UI-UX" in cat:* labels.
// Build a slug→display map to round-trip categories back to their config form.
function buildCategorySlugMap(categories) {
  const map = {};
  for (const cat of categories) {
    map[cat.replace(/\//g, "-").toLowerCase()] = cat;
  }
  return map;
}

function unslugCategory(rawValue, slugMap) {
  if (!rawValue) return "";
  return slugMap[rawValue.toLowerCase()] || rawValue;
}

function fetchGitHubIssues(repo) {
  try {
    execSync("gh --version", { stdio: "ignore" });
  } catch {
    console.error("Error: 'gh' CLI not found. Install from https://cli.github.com/");
    process.exit(1);
  }
  try {
    const json = execSync(
      `gh issue list --repo ${repo} --state all --json number,title,body,state,labels,assignees,createdAt,updatedAt --limit 200`,
      { encoding: "utf8", maxBuffer: 10 * 1024 * 1024 }
    );
    return JSON.parse(json);
  } catch (err) {
    console.error(`Error fetching issues from ${repo}: ${err.message}`);
    process.exit(1);
  }
}

function issueToItem(issue, slugMap) {
  const labelNames = (issue.labels || []).map((l) => l.name);
  const statusLabel = labelNames.find((n) => /^status:/i.test(n));
  const status = statusLabel
    ? STATUS_LABEL_MAP[statusLabel.slice("status:".length).toLowerCase()] ||
      "Captured"
    : issue.state === "CLOSED"
      ? "Done"
      : "Captured";
  const priority = labelNames.find((n) => /^P[1-4]$/.test(n)) || "Unset";
  const rawCat = (labelNames.find((n) => /^cat:/i.test(n)) || "").slice(4);
  const cbcLabel = labelNames.find((n) => /^cbc:/i.test(n));
  const cbcVal = cbcLabel ? parseInt(cbcLabel.slice("cbc:".length), 10) : NaN;
  return {
    id: `#${issue.number}`,
    title: issue.title,
    description: issue.body || "",
    category: unslugCategory(rawCat, slugMap),
    status,
    priority,
    tags: labelNames.filter(
      (n) =>
        !/^(status:|cat:|effort:|complexity:|cbc:|source:|archived$)/i.test(n) &&
        !/^P[1-4]$/.test(n)
    ),
    cbc_score: Number.isFinite(cbcVal) ? cbcVal : null,
    blocked_by: [],
    devops_wis: [],
    target_date: null,
    assigned_to:
      (issue.assignees && issue.assignees[0] && issue.assignees[0].login) ||
      null,
    updated: issue.updatedAt ? issue.updatedAt.slice(0, 10) : null,
    notes: []
  };
}

function loadFromGitHub(repo) {
  const slugMap = buildCategorySlugMap(loadConfiguredCategories());
  const issues = fetchGitHubIssues(repo);
  const items = [];
  const archived = [];
  for (const issue of issues) {
    const labelNames = (issue.labels || []).map((l) => l.name);
    const isArchived = labelNames.some((n) => /^archived$/i.test(n));
    const item = issueToItem(issue, slugMap);
    if (isArchived) archived.push(item);
    else items.push(item);
  }
  return { items, archived };
}

// ---------------------------------------------------------------------------
// Load items
// ---------------------------------------------------------------------------

let backlogItems, archiveItems;

if (BACKEND === "github") {
  const result = loadFromGitHub(REPO);
  backlogItems = result.items;
  archiveItems = result.archived;
} else {
  const backlogData = yaml.load(fs.readFileSync(BACKLOG_FILE, "utf8"));
  backlogItems = (backlogData && backlogData.items) || [];
  archiveItems = [];
  if (fs.existsSync(ARCHIVE_FILE)) {
    const archiveData = yaml.load(fs.readFileSync(ARCHIVE_FILE, "utf8"));
    archiveItems = (archiveData && archiveData.items) || [];
  }
}

const allItems = [...backlogItems, ...archiveItems];

// Status counts (active items only)
const statusBuckets = {
  Captured: 0,
  Evaluated: 0,
  Prioritized: 0,
  Ready: 0,
  "In Progress": 0,
  Done: 0,
  Deferred: 0
};
for (const item of backlogItems) {
  if (item.status in statusBuckets) statusBuckets[item.status]++;
}

// Category counts (active items only)
const categoryBuckets = {};
for (const item of backlogItems) {
  categoryBuckets[item.category] = (categoryBuckets[item.category] || 0) + 1;
}

// Priority counts (active items only)
const priorityBuckets = { P1: 0, P2: 0, P3: 0, P4: 0, Unset: 0 };
for (const item of backlogItems) {
  if (item.priority in priorityBuckets) priorityBuckets[item.priority]++;
}

// Blocked items (active with non-empty blocked_by)
const blocked = backlogItems.filter(
  (i) => Array.isArray(i.blocked_by) && i.blocked_by.length > 0
).length;

// Needs triage (Captured status = not yet evaluated)
const needsTriage = backlogItems.filter((i) => i.status === "Captured").length;

// CBC score distribution
const cbcBuckets = { 5: 0, 4: 0, 3: 0, 2: 0, 1: 0, null: 0 };
for (const item of backlogItems) {
  const score = item.cbc_score != null ? item.cbc_score : null;
  if (score in cbcBuckets) cbcBuckets[score]++;
  else cbcBuckets[null]++;
}

// WI coverage
const withWis = backlogItems.filter(
  (i) => Array.isArray(i.devops_wis) && i.devops_wis.length > 0
).length;
const withoutWis = backlogItems.length - withWis;

// Last grooming — scan all notes for grooming/triage/prioritize keywords
let lastGrooming = null;
const groomingRe = /grooming|triage|prioritize/i;

for (const item of allItems) {
  if (!Array.isArray(item.notes)) continue;
  for (const note of item.notes) {
    if (!note) continue;
    const text = typeof note === "string" ? note : note.text || "";
    const noteDate = typeof note === "object" ? note.date : null;
    if (groomingRe.test(text) && noteDate) {
      const dateStr = String(noteDate);
      if (/^\d{4}-\d{2}-\d{2}$/.test(dateStr)) {
        if (!lastGrooming || dateStr > lastGrooming) lastGrooming = dateStr;
      }
    }
  }
}

// Grooming overdue: null or older than 14 days
let groomingOverdue = true;
if (lastGrooming) {
  const groomDate = new Date(lastGrooming + "T00:00:00Z");
  const now = new Date();
  const diffDays = (now - groomDate) / (1000 * 60 * 60 * 24);
  groomingOverdue = diffDays > 14;
}

// Upcoming milestones (items with target_date in the future, sorted ascending)
const todayStr = new Date().toISOString().slice(0, 10);
const upcoming = backlogItems
  .filter(
    (i) =>
      i.target_date && String(i.target_date) >= todayStr && i.status !== "Done"
  )
  .sort((a, b) => String(a.target_date).localeCompare(String(b.target_date)))
  .map((i) => ({
    id: i.id,
    title: i.title,
    target_date: String(i.target_date)
  }));

// P1/P2 items
const p1p2 = backlogItems
  .filter((i) => i.priority === "P1" || i.priority === "P2")
  .map((i) => ({
    id: i.id,
    title: i.title,
    status: i.status,
    assigned_to: i.assigned_to || null
  }));

const stats = {
  total: backlogItems.length,
  by_status: statusBuckets,
  by_category: categoryBuckets,
  by_priority: priorityBuckets,
  by_cbc: cbcBuckets,
  archived: archiveItems.length,
  blocked,
  needs_triage: needsTriage,
  with_wis: withWis,
  without_wis: withoutWis,
  last_grooming: lastGrooming,
  grooming_overdue: groomingOverdue,
  upcoming_milestones: upcoming,
  p1_p2_items: p1p2
};

if (!tableMode) {
  console.log(JSON.stringify(stats, null, 2));
} else {
  console.log("=== Backlog Statistics ===\n");
  console.log(`Total active items: ${stats.total}`);
  console.log(`Archived items:     ${stats.archived}`);
  console.log(`Blocked items:      ${stats.blocked}`);
  console.log(`Needs triage:       ${stats.needs_triage}`);
  console.log(`With DevOps WIs:    ${stats.with_wis}`);
  console.log(`Without DevOps WIs: ${stats.without_wis}`);
  console.log(`Last grooming:      ${stats.last_grooming || "Never"}`);
  console.log(`Grooming overdue:   ${stats.grooming_overdue ? "YES" : "No"}`);

  console.log("\n--- By Status ---");
  for (const [k, v] of Object.entries(stats.by_status)) {
    console.log(`  ${k.padEnd(15)} ${v}`);
  }

  console.log("\n--- By Category ---");
  for (const [k, v] of Object.entries(stats.by_category)) {
    console.log(`  ${k.padEnd(15)} ${v}`);
  }

  console.log("\n--- By Priority ---");
  for (const [k, v] of Object.entries(stats.by_priority)) {
    console.log(`  ${k.padEnd(15)} ${v}`);
  }

  console.log("\n--- By CBC Score ---");
  const cbcLabels = {
    5: "5 (Ship it)",
    4: "4 (High)",
    3: "3 (Moderate)",
    2: "2 (Low)",
    1: "1 (Eval)",
    null: "Not scored"
  };
  for (const [k, v] of Object.entries(stats.by_cbc)) {
    const label = cbcLabels[k] || k;
    console.log(`  ${label.padEnd(15)} ${v}`);
  }

  if (stats.p1_p2_items.length > 0) {
    console.log("\n--- P1/P2 Items ---");
    console.log("  ID        Status          Assigned        Title");
    console.log("  " + "-".repeat(70));
    for (const item of stats.p1_p2_items) {
      const assigned = item.assigned_to || "(unassigned)";
      console.log(
        `  ${item.id.padEnd(10)}${item.status.padEnd(16)}${assigned.padEnd(16)}${item.title}`
      );
    }
  }

  if (stats.upcoming_milestones.length > 0) {
    console.log("\n--- Upcoming Milestones ---");
    console.log("  ID        Target Date   Title");
    console.log("  " + "-".repeat(60));
    for (const m of stats.upcoming_milestones) {
      console.log(`  ${m.id.padEnd(10)}${m.target_date.padEnd(14)}${m.title}`);
    }
  }
}
