// Generated by claude-sf-toolkit. Customize for your project.
#!/usr/bin/env node
"use strict";

/**
 * backlog-search.js — Search and filter backlog items
 *
 * Usage:
 *   node scripts/backlog-search.js [filters...] [options]
 *
 * Filters (AND logic):
 *   category:X       Filter by category
 *   tag:X            Filter by tag
 *   status:X         Filter by status
 *   priority:X       Filter by priority
 *   assigned:X       Filter by assignee (partial match)
 *   blocked          Show only blocked items
 *   no-wi            Show items without DevOps work items
 *   needs-design     Show items tagged needs-design without a design doc
 *   "free text"      Search title, description, and notes
 *
 * Options:
 *   --backlog-path <path>   Path to backlog.yaml (default: docs/backlog/backlog.yaml)
 *   --archive-path <path>   Path to archive.yaml (default: docs/backlog/archive.yaml)
 *   --json                  Output results as JSON
 *   --count                 Output only the count of matching items
 *   --help                  Show this help message
 */

const fs = require("fs");
const path = require("path");
const yaml = require("js-yaml");

const REPO_ROOT = path.join(__dirname, "..");

// ---------------------------------------------------------------------------
// Argument parsing
// ---------------------------------------------------------------------------

const rawArgs = process.argv.slice(2);

// Check for --help
if (rawArgs.includes("--help")) {
  console.log(
    [
      "Usage: node scripts/backlog-search.js [filters...] [options]",
      "",
      "Filters (AND logic):",
      "  category:X       Filter by category",
      "  tag:X            Filter by tag",
      "  status:X         Filter by status",
      "  priority:X       Filter by priority",
      "  assigned:X       Filter by assignee (partial match)",
      "  blocked          Show only blocked items",
      "  no-wi            Show items without DevOps work items",
      "  needs-design     Show items tagged needs-design without a design doc",
      '  "free text"      Search title, description, and notes',
      "",
      "Options:",
      "  --backlog-path <path>   Path to backlog.yaml (default: docs/backlog/backlog.yaml)",
      "  --archive-path <path>   Path to archive.yaml (default: docs/backlog/archive.yaml)",
      "  --json                  Output results as JSON",
      "  --count                 Output only the count of matching items",
      "  --help                  Show this help message"
    ].join("\n")
  );
  process.exit(0);
}

// Extract named options
const jsonMode = rawArgs.includes("--json");
const countMode = rawArgs.includes("--count");

let backlogPath = "docs/backlog/backlog.yaml";
let archivePath = "docs/backlog/archive.yaml";

const filters = [];
for (let i = 0; i < rawArgs.length; i++) {
  if (rawArgs[i] === "--json" || rawArgs[i] === "--count") continue;
  if (rawArgs[i] === "--backlog-path") {
    backlogPath = rawArgs[++i];
    continue;
  }
  if (rawArgs[i] === "--archive-path") {
    archivePath = rawArgs[++i];
    continue;
  }
  filters.push(rawArgs[i]);
}

if (filters.length === 0) {
  console.error("Usage: backlog-search.js [filters...] [--json] [--count]");
  console.error(
    'Filters: category:X  tag:X  status:X  priority:X  assigned:X  blocked  no-wi  needs-design  "free text"'
  );
  process.exit(1);
}

const BACKLOG_FILE = path.resolve(REPO_ROOT, backlogPath);
const ARCHIVE_FILE = path.resolve(REPO_ROOT, archivePath);

// Load items
const backlogData = yaml.load(fs.readFileSync(BACKLOG_FILE, "utf8"));
let items = [...((backlogData && backlogData.items) || [])];

if (fs.existsSync(ARCHIVE_FILE)) {
  const archiveData = yaml.load(fs.readFileSync(ARCHIVE_FILE, "utf8"));
  items = items.concat((archiveData && archiveData.items) || []);
}

// Build filter functions (AND logic)
const predicates = [];

for (const filter of filters) {
  const colonIdx = filter.indexOf(":");
  if (colonIdx > 0) {
    const key = filter.slice(0, colonIdx).toLowerCase();
    const val = filter.slice(colonIdx + 1);

    switch (key) {
      case "category":
        predicates.push(
          (i) => i.category && i.category.toLowerCase() === val.toLowerCase()
        );
        break;
      case "tag":
        predicates.push(
          (i) =>
            Array.isArray(i.tags) &&
            i.tags.some((t) => t.toLowerCase() === val.toLowerCase())
        );
        break;
      case "status":
        predicates.push(
          (i) => i.status && i.status.toLowerCase() === val.toLowerCase()
        );
        break;
      case "priority":
        predicates.push(
          (i) => i.priority && i.priority.toLowerCase() === val.toLowerCase()
        );
        break;
      case "assigned":
        predicates.push((i) => {
          const assignee = i.assigned_to || "";
          return assignee.toLowerCase().includes(val.toLowerCase());
        });
        break;
      default:
        // Treat unknown key:val as free text
        predicates.push(makeFreeTextPredicate(filter));
        break;
    }
  } else if (filter === "blocked") {
    predicates.push(
      (i) => Array.isArray(i.blocked_by) && i.blocked_by.length > 0
    );
  } else if (filter === "no-wi") {
    predicates.push(
      (i) => !Array.isArray(i.devops_wis) || i.devops_wis.length === 0
    );
  } else if (filter === "needs-design") {
    predicates.push(
      (i) =>
        Array.isArray(i.tags) &&
        i.tags.includes("needs-design") &&
        (i.design_doc == null || i.design_doc === "")
    );
  } else {
    // Free text search
    predicates.push(makeFreeTextPredicate(filter));
  }
}

function makeFreeTextPredicate(query) {
  const q = query.toLowerCase();
  return (item) => {
    // Search title
    if (item.title && item.title.toLowerCase().includes(q)) return true;
    // Search description
    if (item.description && item.description.toLowerCase().includes(q))
      return true;
    // Search notes text
    if (Array.isArray(item.notes)) {
      for (const note of item.notes) {
        if (!note) continue;
        const text = typeof note === "string" ? note : note.text || "";
        if (text.toLowerCase().includes(q)) return true;
      }
    }
    return false;
  };
}

// Apply all filters (AND)
const results = items.filter((item) => predicates.every((p) => p(item)));

// Output
if (countMode) {
  console.log(results.length);
} else if (jsonMode) {
  console.log(JSON.stringify(results, null, 2));
} else {
  // Markdown table
  if (results.length === 0) {
    console.log("No matching items found.");
    process.exit(0);
  }

  console.log("| ID | Title | Category | Status | Priority | Effort | Tags |");
  console.log("|---|---|---|---|---|---|---|");
  for (const item of results) {
    const tags = Array.isArray(item.tags) ? item.tags.join(", ") : "";
    const title = (item.title || "").replace(/\|/g, "\\|");
    console.log(
      `| ${item.id} | ${title} | ${item.category} | ${item.status} | ${item.priority} | ${item.effort} | ${tags} |`
    );
  }
  console.log(`\n${results.length} item(s) found.`);
}
