// Generated by claude-sf-toolkit. Customize for your project.
/**
 * backlog-add.js — Add a new item to backlog.yaml
 *
 * Usage:
 *   node scripts/backlog-add.js --title "Item title" --description "Desc" --category Platform [options]
 *
 * Options:
 *   --backlog-path <path>   Path to backlog.yaml (default: docs/backlog/backlog.yaml)
 *   --tags-path <path>      Path to tags.yaml (default: docs/backlog/tags.yaml)
 *   --title <text>          Item title (required)
 *   --description <text>    Item description (required)
 *   --category <name>       Category (required): reads valid values from config/sf-toolkit.json → backlog.categories
 *   --status <status>       Initial status (default: Captured)
 *   --priority <P1-P4>      Priority level (default: Unset)
 *   --effort <S|M|L|XL>     Effort estimate (default: Unset)
 *   --complexity <Low|Med|High>  Complexity (default: Unset)
 *   --tags <tag1,tag2>      Comma-separated tags
 *   --source <source>       Source type (default: team-member)
 *   --submitted-by <name>   Submitter name (default: git user.name)
 *   --assigned-to <name>    Assignee name
 *   --target-date <YYYY-MM-DD>  Target date
 *   --design-doc <path>     Path to design document
 *   --devops-wis <WI-NNNNNN,...>  Comma-separated work item IDs
 *   --blocked-by <BL-NNNN,...>    Comma-separated blocking item IDs
 *   --related <BL-NNNN,...>       Comma-separated related item IDs
 *   --note <text>           Initial note text
 *   --json                  Output added item as JSON
 *   --help                  Show this help message
 *
 * Exit codes: 0 = success, 1 = validation error, 2 = file error
 */

const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");
const yaml = require("js-yaml");

const REPO_ROOT = path.join(__dirname, "..");

/**
 * Load categories from config/sf-toolkit.json → backlog.categories.
 * Falls back to extracting unique categories from backlog items.
 */
function loadCategories(items) {
  const configPath = path.resolve(REPO_ROOT, "config/sf-toolkit.json");
  try {
    const config = JSON.parse(fs.readFileSync(configPath, "utf8"));
    if (config.backlog && Array.isArray(config.backlog.categories) && config.backlog.categories.length > 0) {
      return config.backlog.categories;
    }
  } catch {
    // Config missing or invalid — fall through
  }
  const seen = [...new Set((items || []).map((i) => i.category).filter(Boolean))];
  return seen.sort();
}
const VALID_STATUSES = ["Captured", "Evaluated", "Prioritized", "Deferred"];
const VALID_PRIORITIES = ["P1", "P2", "P3", "P4", "Unset"];
const VALID_EFFORTS = ["S", "M", "L", "XL", "Unset"];
const VALID_COMPLEXITIES = ["Low", "Med", "High", "Unset"];
const VALID_SOURCES = [
  "team-member",
  "stakeholder-request",
  "vendor-eval",
  "claude-session"
];

// ---------------------------------------------------------------------------
// Argument parsing
// ---------------------------------------------------------------------------

function parseArgs(argv) {
  const args = {};
  let i = 2; // skip node and script path
  while (i < argv.length) {
    const key = argv[i];
    if (key === "--help") {
      console.log(
        [
          "Usage: node scripts/backlog-add.js --title \"Item title\" --description \"Desc\" --category Platform [options]",
          "",
          "Options:",
          "  --backlog-path <path>   Path to backlog.yaml (default: docs/backlog/backlog.yaml)",
          "  --tags-path <path>      Path to tags.yaml (default: docs/backlog/tags.yaml)",
          "  --title <text>          Item title (required)",
          "  --description <text>    Item description (required)",
          "  --category <name>       Category (required)",
          "  --status <status>       Initial status (default: Captured)",
          "  --priority <P1-P4>      Priority level (default: Unset)",
          "  --effort <S|M|L|XL>     Effort estimate (default: Unset)",
          "  --complexity <Low|Med|High>  Complexity (default: Unset)",
          "  --tags <tag1,tag2>      Comma-separated tags",
          "  --source <source>       Source type (default: team-member)",
          "  --submitted-by <name>   Submitter name (default: git user.name)",
          "  --assigned-to <name>    Assignee name",
          "  --target-date <YYYY-MM-DD>  Target date",
          "  --design-doc <path>     Path to design document",
          "  --devops-wis <WI-NNNNNN,...>  Comma-separated work item IDs",
          "  --blocked-by <BL-NNNN,...>    Comma-separated blocking item IDs",
          "  --related <BL-NNNN,...>       Comma-separated related item IDs",
          "  --note <text>           Initial note text",
          "  --json                  Output added item as JSON",
          "  --help                  Show this help message"
        ].join("\n")
      );
      process.exit(0);
    }
    if (key.startsWith("--")) {
      const name = key.slice(2);
      // Boolean flag (no value) — only --json is boolean
      if (name === "json") {
        args[name] = true;
        i++;
      } else {
        if (i + 1 >= argv.length) {
          console.error(`Error: --${name} requires a value`);
          process.exit(1);
        }
        args[name] = argv[i + 1];
        i += 2;
      }
    } else {
      console.error(`Error: unexpected argument "${key}"`);
      process.exit(1);
    }
  }
  return args;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function today() {
  return new Date().toISOString().slice(0, 10);
}

function gitUserName() {
  try {
    return execSync("git config user.name", { encoding: "utf8" }).trim();
  } catch {
    return "Unknown";
  }
}

function padId(n) {
  return `BL-${String(n).padStart(4, "0")}`;
}

function postProcessYaml(yamlStr) {
  // Ensure BL-NNNN and WI-NNNNNN values are double-quoted
  let result = yamlStr;

  // Fix unquoted BL-NNNN in block sequences (- BL-0001)
  result = result.replace(/^(\s*- )(BL-\d{4})$/gm, '$1"$2"');

  // Fix unquoted WI-NNNNNN in block sequences (- WI-000044)
  result = result.replace(/^(\s*- )(WI-\d{6})$/gm, '$1"$2"');

  // Fix unquoted id field values
  result = result.replace(/^(\s*id:\s+)(BL-\d{4})$/gm, '$1"$2"');

  return result;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main() {
  const args = parseArgs(process.argv);

  const BACKLOG_PATH = path.resolve(
    REPO_ROOT,
    args["backlog-path"] || "docs/backlog/backlog.yaml"
  );
  const TAGS_PATH = path.resolve(
    REPO_ROOT,
    args["tags-path"] || "docs/backlog/tags.yaml"
  );

  // --- Required args ---
  if (!args.title) {
    console.error("Error: --title is required");
    process.exit(1);
  }
  if (!args.description) {
    console.error("Error: --description is required");
    process.exit(1);
  }
  if (!args.category) {
    console.error("Error: --category is required");
    process.exit(1);
  }

  // --- Read files ---
  let backlogRaw, tagsRaw;
  try {
    backlogRaw = fs.readFileSync(BACKLOG_PATH, "utf8");
  } catch (err) {
    console.error(`Error: cannot read backlog.yaml — ${err.message}`);
    process.exit(2);
  }
  try {
    tagsRaw = fs.readFileSync(TAGS_PATH, "utf8");
  } catch (err) {
    console.error(`Error: cannot read tags.yaml — ${err.message}`);
    process.exit(2);
  }

  const backlog = yaml.load(backlogRaw);
  const tagsDoc = yaml.load(tagsRaw);
  const validTags = tagsDoc.tags || [];

  // --- Validate category ---
  const validCategories = loadCategories(backlog.items || []);
  if (validCategories.length > 0 && !validCategories.includes(args.category)) {
    console.error(
      `Error: invalid category "${args.category}". Must be one of: ${validCategories.join(", ")}`
    );
    process.exit(1);
  }

  // --- Validate status ---
  const status = args.status || "Captured";
  if (!VALID_STATUSES.includes(status)) {
    console.error(
      `Error: invalid status "${status}". Must be one of: ${VALID_STATUSES.join(", ")}`
    );
    process.exit(1);
  }

  // --- Validate priority ---
  const priority = args.priority || "Unset";
  if (!VALID_PRIORITIES.includes(priority)) {
    console.error(
      `Error: invalid priority "${priority}". Must be one of: ${VALID_PRIORITIES.join(", ")}`
    );
    process.exit(1);
  }

  // --- Validate effort ---
  const effort = args.effort || "Unset";
  if (!VALID_EFFORTS.includes(effort)) {
    console.error(
      `Error: invalid effort "${effort}". Must be one of: ${VALID_EFFORTS.join(", ")}`
    );
    process.exit(1);
  }

  // --- Validate complexity ---
  const complexity = args.complexity || "Unset";
  if (!VALID_COMPLEXITIES.includes(complexity)) {
    console.error(
      `Error: invalid complexity "${complexity}". Must be one of: ${VALID_COMPLEXITIES.join(", ")}`
    );
    process.exit(1);
  }

  // --- Validate tags ---
  let tags = [];
  if (args.tags) {
    tags = args.tags
      .split(",")
      .map((t) => t.trim())
      .filter(Boolean);
    const invalid = tags.filter((t) => !validTags.includes(t));
    if (invalid.length > 0) {
      console.error(
        `Error: invalid tags: ${invalid.join(", ")}. Valid tags: ${validTags.join(", ")}`
      );
      process.exit(1);
    }
  }

  // --- Validate source ---
  const source = args.source || "team-member";
  if (!VALID_SOURCES.includes(source)) {
    console.error(
      `Error: invalid source "${source}". Must be one of: ${VALID_SOURCES.join(", ")}`
    );
    process.exit(1);
  }

  // --- Validate devops_wis ---
  let devopsWis = [];
  if (args["devops-wis"]) {
    devopsWis = args["devops-wis"]
      .split(",")
      .map((w) => w.trim())
      .filter(Boolean);
    const wiPattern = /^WI-\d{6}$/;
    const invalidWis = devopsWis.filter((w) => !wiPattern.test(w));
    if (invalidWis.length > 0) {
      console.error(
        `Error: invalid WI format: ${invalidWis.join(", ")}. Must match WI-NNNNNN.`
      );
      process.exit(1);
    }
  }

  // --- Validate design_doc path ---
  const designDoc = args["design-doc"] || null;
  if (designDoc) {
    const fullPath = path.join(REPO_ROOT, designDoc);
    if (!fs.existsSync(fullPath)) {
      console.error(`Error: design_doc path does not exist: ${designDoc}`);
      process.exit(1);
    }
  }

  // --- Collect existing IDs for blocked_by / related validation ---
  const existingIds = new Set((backlog.items || []).map((item) => item.id));

  // --- Validate blocked_by ---
  let blockedBy = [];
  if (args["blocked-by"]) {
    blockedBy = args["blocked-by"]
      .split(",")
      .map((b) => b.trim())
      .filter(Boolean);
    const invalidBlocked = blockedBy.filter((b) => !existingIds.has(b));
    if (invalidBlocked.length > 0) {
      console.error(
        `Error: blocked_by references non-existent items: ${invalidBlocked.join(", ")}`
      );
      process.exit(1);
    }
  }

  // --- Validate related ---
  let related = [];
  if (args.related) {
    related = args.related
      .split(",")
      .map((r) => r.trim())
      .filter(Boolean);
    const invalidRelated = related.filter((r) => !existingIds.has(r));
    if (invalidRelated.length > 0) {
      console.error(
        `Error: related references non-existent items: ${invalidRelated.join(", ")}`
      );
      process.exit(1);
    }
  }

  // --- Validate target_date ---
  const targetDate = args["target-date"] || null;
  if (targetDate && !/^\d{4}-\d{2}-\d{2}$/.test(targetDate)) {
    console.error(
      `Error: invalid target-date format "${targetDate}". Must be YYYY-MM-DD.`
    );
    process.exit(1);
  }

  // --- Build new item ---
  const submittedBy = args["submitted-by"] || gitUserName();
  const assignedTo = args["assigned-to"] || null;
  const noteText = args.note || "Added via backlog-add.js";
  const todayStr = today();
  const newId = padId(backlog.next_id);

  const newItem = {
    id: newId,
    title: args.title,
    description: args.description + "\n",
    category: args.category,
    status: status,
    priority: priority === "Unset" ? null : priority,
    effort: effort === "Unset" ? null : effort,
    complexity: complexity === "Unset" ? null : complexity,
    tags: tags,
    source: source,
    submitted_by: submittedBy,
    assigned_to: assignedTo,
    target_date: targetDate,
    design_doc: designDoc,
    devops_wis: devopsWis,
    blocked_by: blockedBy,
    related: related,
    created: todayStr,
    updated: todayStr,
    notes: [
      {
        date: todayStr,
        author: submittedBy,
        text: noteText
      }
    ]
  };

  // --- Append item and update metadata ---
  if (!backlog.items) {
    backlog.items = [];
  }
  backlog.items.push(newItem);
  backlog.next_id = backlog.next_id + 1;
  backlog.last_updated = todayStr;

  // --- Serialize and write ---
  try {
    let yamlStr = yaml.dump(backlog, {
      lineWidth: 120,
      noRefs: true,
      quotingType: '"',
      flowLevel: -1,
      sortKeys: false
    });

    yamlStr = postProcessYaml(yamlStr);

    fs.writeFileSync(BACKLOG_PATH, yamlStr, "utf8");
  } catch (err) {
    console.error(`Error: cannot write backlog.yaml — ${err.message}`);
    process.exit(2);
  }

  // --- Output ---
  if (args.json) {
    // For JSON output, convert nulls to "Unset" for priority/effort/complexity display
    const jsonItem = { ...newItem };
    if (jsonItem.priority === null) jsonItem.priority = "Unset";
    if (jsonItem.effort === null) jsonItem.effort = "Unset";
    if (jsonItem.complexity === null) jsonItem.complexity = "Unset";
    // Remove trailing newline from description for clean JSON
    jsonItem.description = jsonItem.description.trimEnd();
    console.log(JSON.stringify(jsonItem, null, 2));
  } else {
    console.log(
      `Added ${newId}: ${args.title} (status: ${status}, category: ${args.category})`
    );
  }

  process.exit(0);
}

main();
