// Generated by claude-sf-toolkit. Customize for your project.
/**
 * backlog-add.js — Add a new backlog item as a GitHub Issue.
 *
 * Usage:
 *   node scripts/backlog-add.js --repo owner/repo --title "Item title" --description "Desc" --category Platform [options]
 *
 * Options:
 *   --repo <owner/repo>     GitHub repo (required)
 *   --backend <github>      Data backend (optional; 'github' is the only supported backend)
 *   --title <text>          Item title (required)
 *   --description <text>    Item description (required)
 *   --category <name>       Category (required); becomes a cat:{slug} label
 *   --status <status>       Initial status (default: Captured)
 *   --priority <P1-P4>      Priority level (default: Unset)
 *   --effort <S|M|L|XL>     Effort estimate (default: Unset)
 *   --complexity <Low|Med|High>  Complexity (default: Unset)
 *   --tags <tag1,tag2>      Comma-separated tags; each becomes a tag:{value} label
 *   --source <source>       Item source (default: team-member); becomes a source:{value} label
 *   --assigned-to <name>    Assignee GitHub login
 *   --target-date <YYYY-MM-DD>  Target date (recorded in the issue body)
 *   --design-doc <path>     Path to design document
 *   --blocked-by <ref,...>  Comma-separated blocking issue refs (recorded in the issue body)
 *   --related <ref,...>     Comma-separated related issue refs (recorded in the issue body)
 *   --json                  Output added item as JSON
 *   --help                  Show this help message
 *
 * Exit codes: 0 = success, 1 = validation error, 2 = file error
 */

const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");

// Translate canonical source values to the GitHub label short-forms created
// by commands/setup.md. Without this, the script emits
// `source:claude-session` but the repo only has `source:claude`, causing
// `gh issue create` to fail label lookup.
const SOURCE_LABEL_MAP = {
  "team-member": "team",
  "stakeholder-request": "stakeholder",
  "vendor-eval": "vendor",
  "claude-session": "claude"
};

function sourceToLabel(source) {
  return SOURCE_LABEL_MAP[source] || source;
}

// ---------------------------------------------------------------------------
// Argument parsing
// ---------------------------------------------------------------------------

function parseArgs(argv) {
  const args = {};
  let i = 2; // skip node and script path
  while (i < argv.length) {
    const key = argv[i];
    if (key === "--help") {
      console.log(
        [
          "Usage: node scripts/backlog-add.js --repo owner/repo --title \"Item title\" --description \"Desc\" --category Platform [options]",
          "",
          "Options:",
          "  --repo <owner/repo>     GitHub repo (required)",
          "  --backend <github>      Data backend (optional; 'github' is the only supported backend)",
          "  --title <text>          Item title (required)",
          "  --description <text>    Item description (required)",
          "  --category <name>       Category (required)",
          "  --status <status>       Initial status (default: Captured)",
          "  --priority <P1-P4>      Priority level (default: Unset)",
          "  --effort <S|M|L|XL>     Effort estimate (default: Unset)",
          "  --complexity <Low|Med|High>  Complexity (default: Unset)",
          "  --tags <tag1,tag2>      Comma-separated tags (each becomes a tag:{value} label)",
          "  --source <source>       Item source field (default: team-member)",
          "  --assigned-to <name>    Assignee GitHub login",
          "  --target-date <YYYY-MM-DD>  Target date (recorded in the issue body)",
          "  --design-doc <path>     Path to design document",
          "  --blocked-by <ref,...>  Comma-separated blocking issue refs (issue body)",
          "  --related <ref,...>     Comma-separated related issue refs (issue body)",
          "  --json                  Output added item as JSON",
          "  --help                  Show this help message"
        ].join("\n")
      );
      process.exit(0);
    }
    if (key.startsWith("--")) {
      const name = key.slice(2);
      // Boolean flag (no value) — only --json is boolean
      if (name === "json") {
        args[name] = true;
        i++;
      } else {
        if (i + 1 >= argv.length) {
          console.error(`Error: --${name} requires a value`);
          process.exit(1);
        }
        args[name] = argv[i + 1];
        i += 2;
      }
    } else {
      console.error(`Error: unexpected argument "${key}"`);
      process.exit(1);
    }
  }
  return args;
}

// ---------------------------------------------------------------------------
// GitHub Issues backend
// ---------------------------------------------------------------------------

// GitHub labels can't contain "/", so "UI/UX" becomes "UI-UX" when slugged.
function slugForLabel(value) {
  return String(value).replace(/\//g, "-");
}

function buildIssueBody({
  description,
  category,
  source,
  cbcScore,
  blockedBy,
  related,
  designDoc,
  targetDate
}) {
  const lines = [description.trim(), ""];
  lines.push("## Details");
  lines.push(`- **Category:** ${category}`);
  lines.push(`- **Source:** ${source}`);
  lines.push(`- **CBC Score:** ${cbcScore != null ? `${cbcScore}/5` : "(not scored)"}`);
  if (targetDate) lines.push(`- **Target:** ${targetDate}`);
  lines.push("");
  lines.push("## Dependencies");
  lines.push(
    `- **Blocked by:** ${blockedBy && blockedBy.length ? blockedBy.join(", ") : "(none)"}`
  );
  lines.push(
    `- **Related:** ${related && related.length ? related.join(", ") : "(none)"}`
  );
  lines.push("");
  lines.push("## Design");
  lines.push(designDoc || "(none)");
  lines.push("");
  return lines.join("\n");
}

function runGhCreateIssue({ repo, title, body, labels, assignee }) {
  try {
    execSync("gh --version", { stdio: "ignore" });
  } catch {
    console.error("Error: 'gh' CLI not found. Install from https://cli.github.com/");
    process.exit(2);
  }

  // Write body to temp file to avoid shell-escaping issues
  const tmpDir = require("os").tmpdir();
  const tmpPath = path.join(tmpDir, `backlog-add-${process.pid}-${Date.now()}.md`);
  fs.writeFileSync(tmpPath, body, "utf8");

  try {
    const labelArgs = labels
      .filter(Boolean)
      .map((l) => `--label ${JSON.stringify(l)}`)
      .join(" ");
    const assigneeArg = assignee ? `--assignee ${JSON.stringify(assignee)}` : "";
    const cmd = `gh issue create --repo ${JSON.stringify(repo)} --title ${JSON.stringify(title)} --body-file ${JSON.stringify(tmpPath)} ${labelArgs} ${assigneeArg}`;
    const out = execSync(cmd, { encoding: "utf8" }).trim();
    // `gh issue create` prints the URL of the created issue
    const match = out.match(/\/issues\/(\d+)/);
    const number = match ? match[1] : null;
    return { url: out, number };
  } catch (err) {
    console.error(`Error creating GitHub issue: ${err.message}`);
    process.exit(2);
  } finally {
    try {
      fs.unlinkSync(tmpPath);
    } catch {
      // best effort
    }
  }
}

function addToGitHub(args, repo) {
  if (!args.title) {
    console.error("Error: --title is required");
    process.exit(1);
  }
  if (!args.description) {
    console.error("Error: --description is required");
    process.exit(1);
  }
  if (!args.category) {
    console.error("Error: --category is required");
    process.exit(1);
  }

  const status = (args.status || "Captured").toLowerCase().replace(/\s+/g, "-");
  const priority = args.priority || "Unset";
  const effort = args.effort || "Unset";
  const complexity = args.complexity || "Unset";
  const source = args.source || "team-member";
  const tags = args.tags
    ? args.tags
        .split(",")
        .map((t) => t.trim())
        .filter(Boolean)
    : [];

  const labels = [
    `status:${status}`,
    `cat:${slugForLabel(args.category)}`,
    `source:${sourceToLabel(source)}`
  ];
  if (priority !== "Unset") labels.push(priority);
  if (effort !== "Unset") labels.push(`effort:${effort}`);
  if (complexity !== "Unset") labels.push(`complexity:${complexity.toLowerCase()}`);
  for (const t of tags) labels.push(`tag:${t}`);

  const body = buildIssueBody({
    description: args.description,
    category: args.category,
    source,
    cbcScore: null,
    blockedBy: args["blocked-by"]
      ? args["blocked-by"].split(",").map((s) => s.trim()).filter(Boolean)
      : [],
    related: args.related
      ? args.related.split(",").map((s) => s.trim()).filter(Boolean)
      : [],
    designDoc: args["design-doc"] || null,
    targetDate: args["target-date"] || null
  });

  const result = runGhCreateIssue({
    repo,
    title: args.title,
    body,
    labels,
    assignee: args["assigned-to"] || null
  });

  if (args.json) {
    console.log(
      JSON.stringify(
        {
          id: `#${result.number}`,
          title: args.title,
          category: args.category,
          status: args.status || "Captured",
          priority,
          effort,
          complexity,
          source,
          tags,
          url: result.url
        },
        null,
        2
      )
    );
  } else {
    console.log(
      `Added #${result.number}: ${args.title} (status: ${args.status || "Captured"}, category: ${args.category}) — ${result.url}`
    );
  }

  process.exit(0);
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main() {
  const args = parseArgs(process.argv);

  const BACKEND = (args.backend || "github").toLowerCase();
  const REPO = args.repo || null;

  if (BACKEND !== "github") {
    console.error(
      `Error: --backend must be 'github' (got: ${BACKEND}). GitHub Issues is the only supported backend as of v2.0.0.`
    );
    process.exit(1);
  }
  if (!REPO) {
    console.error("Error: --repo <owner/repo> is required");
    process.exit(1);
  }
  return addToGitHub(args, REPO);
}

main();
