// Generated by claude-sf-toolkit. Customize for your project.
/**
 * backlog-render.js
 *
 * Generates a README.md from backlog.yaml and archive.yaml.
 *
 * Usage:
 *   node scripts/backlog-render.js [options]
 *
 * Options:
 *   --backlog-path <path>   Path to backlog.yaml (default: docs/backlog/backlog.yaml)
 *   --archive-path <path>   Path to archive.yaml (default: docs/backlog/archive.yaml)
 *   --output <path>         Output README.md path (default: docs/backlog/README.md)
 *   --project-name <name>   Project name for header (default: "Project")
 *   --help                  Show this help message
 */
const fs = require("fs");
const path = require("path");
const yaml = require("js-yaml");

// ---------------------------------------------------------------------------
// Configuration — override via CLI args
// ---------------------------------------------------------------------------

const REPO_ROOT = path.join(__dirname, "..");

function parseArgs(argv) {
  const args = {};
  let i = 2;
  while (i < argv.length) {
    const key = argv[i];
    if (key === "--help") {
      console.log(
        [
          "Usage: node scripts/backlog-render.js [options]",
          "",
          "Options:",
          "  --backlog-path <path>   Path to backlog.yaml (default: docs/backlog/backlog.yaml)",
          "  --archive-path <path>   Path to archive.yaml (default: docs/backlog/archive.yaml)",
          "  --output <path>         Output README.md path (default: docs/backlog/README.md)",
          "  --project-name <name>   Project name for header (default: \"Project\")",
          "  --help                  Show this help message"
        ].join("\n")
      );
      process.exit(0);
    }
    if (key.startsWith("--")) {
      const name = key.slice(2);
      if (i + 1 >= argv.length) {
        console.error(`Error: --${name} requires a value`);
        process.exit(1);
      }
      args[name] = argv[i + 1];
      i += 2;
    } else {
      // Positional arg treated as backlog path
      args["backlog-path"] = argv[i];
      i++;
    }
  }
  return args;
}

const CLI_ARGS = parseArgs(process.argv);

const BACKLOG_PATH = path.resolve(
  REPO_ROOT,
  CLI_ARGS["backlog-path"] || "docs/backlog/backlog.yaml"
);
const ARCHIVE_PATH = path.resolve(
  REPO_ROOT,
  CLI_ARGS["archive-path"] || "docs/backlog/archive.yaml"
);
const OUTPUT_PATH = path.resolve(
  REPO_ROOT,
  CLI_ARGS["output"] || "docs/backlog/README.md"
);
const PROJECT_NAME = CLI_ARGS["project-name"] || "Project";

const STATUSES = [
  "Captured",
  "Evaluated",
  "Prioritized",
  "Ready",
  "In Progress",
  "Deferred"
];
const CATEGORIES = ["Platform", "Integrations", "Portal", "Operations"];
const PRIORITIES = ["P1", "P2", "P3", "P4", "Unset"];

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function loadYaml(filePath) {
  const raw = fs.readFileSync(filePath, "utf8");
  return yaml.load(raw);
}

function today() {
  return new Date().toISOString().slice(0, 10);
}

function daysFromNow(dateStr, refDate) {
  if (!dateStr) return Infinity;
  const d = new Date(dateStr);
  return Math.ceil((d - refDate) / (1000 * 60 * 60 * 24));
}

function truncate(str, len) {
  if (!str) return "";
  return str.length > len ? str.slice(0, len - 3) + "..." : str;
}

function designDocCell(doc) {
  if (!doc) return "";
  const basename = path.basename(doc);
  return `[${basename}](../../${doc})`;
}

function pad(str) {
  return str == null ? "" : String(str);
}

function isBlocked(item) {
  return (
    (item.tags && item.tags.includes("blocked")) ||
    (item.blocked_by && item.blocked_by.length > 0)
  );
}

function latestNote(item) {
  if (!item.notes || item.notes.length === 0) return "";
  const last = item.notes[item.notes.length - 1];
  // notes can be plain strings or objects with .text
  if (typeof last === "string") return last;
  return last.text || "";
}

// ---------------------------------------------------------------------------
// Section builders
// ---------------------------------------------------------------------------

function renderHeader() {
  return [
    `# ${PROJECT_NAME} Backlog`,
    "",
    `> Auto-generated from \`backlog.yaml\` by \`scripts/backlog-render.js\` on ${today()}. Do not edit manually.`,
    ""
  ];
}

function renderExecutiveSummary(items) {
  const lines = ["## Executive Summary", ""];
  const now = new Date();

  // In-progress items
  const inProgress = items.filter((i) => i.status === "In Progress");
  const ipCategories = [...new Set(inProgress.map((i) => i.category))];
  lines.push(
    `- **${inProgress.length} item(s) in progress** across ${ipCategories.join(", ") || "none"}`
  );

  // Top 3 Ready/Prioritized P1-P2
  const topReady = items
    .filter(
      (i) =>
        (i.status === "Ready" || i.status === "Prioritized") &&
        (i.priority === "P1" || i.priority === "P2")
    )
    .sort((a, b) => {
      const po = { P1: 1, P2: 2 };
      return (po[a.priority] || 9) - (po[b.priority] || 9);
    })
    .slice(0, 3);
  if (topReady.length) {
    lines.push("- **Top Ready/Prioritized (P1-P2):**");
    for (const item of topReady) {
      lines.push(`  - ${item.id}: ${item.title} (${item.priority})`);
    }
  }

  // Blocked
  const blocked = items.filter(isBlocked);
  if (blocked.length) {
    lines.push(
      `- **${blocked.length} blocked item(s):** ${blocked.map((i) => i.id).join(", ")}`
    );
  }

  // Target dates within 30 days
  const upcoming = items
    .filter(
      (i) =>
        i.target_date &&
        daysFromNow(i.target_date, now) >= 0 &&
        daysFromNow(i.target_date, now) <= 30
    )
    .sort((a, b) => new Date(a.target_date) - new Date(b.target_date));
  if (upcoming.length) {
    lines.push("- **Upcoming target dates (next 30 days):**");
    for (const item of upcoming) {
      lines.push(`  - ${item.id}: ${item.title} — ${item.target_date}`);
    }
  }

  lines.push("");
  return lines;
}

function renderSummaryTable(items, archivedCount) {
  const lines = ["## Summary", ""];
  lines.push("| Status | Count |");
  lines.push("|--------|------:|");
  for (const s of STATUSES) {
    const count = items.filter((i) => i.status === s).length;
    lines.push(`| ${s} | ${count} |`);
  }
  lines.push(`| Archived | ${archivedCount} |`);
  lines.push(`| **Total** | **${items.length + archivedCount}** |`);
  lines.push("");
  return lines;
}

function renderCategoryMatrix(items) {
  const lines = ["## By Category", ""];
  lines.push("| Category | Total | P1 | P2 | P3 | P4 | Unset |");
  lines.push("|----------|------:|---:|---:|---:|---:|------:|");
  for (const cat of CATEGORIES) {
    const catItems = items.filter((i) => i.category === cat);
    const total = catItems.length;
    const counts = PRIORITIES.map(
      (p) => catItems.filter((i) => (i.priority || "Unset") === p).length
    );
    lines.push(`| ${cat} | ${total} | ${counts.join(" | ")} |`);
  }
  lines.push("");
  return lines;
}

function renderPriorityBoard(items) {
  const lines = ["## Priority Board", ""];
  for (const p of PRIORITIES) {
    const pItems = items.filter((i) => (i.priority || "Unset") === p);
    lines.push(`### ${p} (${pItems.length})`, "");
    if (pItems.length === 0) {
      lines.push("No items.", "");
      continue;
    }
    lines.push(
      "| ID | Title | Category | Status | Effort | Complexity | Assigned | WIs | Design Doc |"
    );
    lines.push(
      "|----|-------|----------|--------|--------|------------|----------|-----|------------|"
    );
    for (const item of pItems) {
      const wis = (item.devops_wis || []).join(", ");
      const assigned = item.assigned_to || "";
      lines.push(
        `| ${item.id} | ${item.title} | ${item.category} | ${item.status} | ${pad(item.effort)} | ${pad(item.complexity)} | ${assigned} | ${wis} | ${designDocCell(item.design_doc)} |`
      );
    }
    lines.push("");
  }
  return lines;
}

function renderWiCrossReference(items) {
  const lines = ["## Work Item Cross-Reference", ""];
  const rows = [];
  for (const item of items) {
    if (!item.devops_wis || item.devops_wis.length === 0) continue;
    for (const wi of item.devops_wis) {
      rows.push({
        wi,
        id: item.id,
        title: item.title,
        status: item.status,
        category: item.category
      });
    }
  }
  rows.sort((a, b) => a.wi.localeCompare(b.wi));

  if (rows.length === 0) {
    lines.push("No items with linked work items.", "");
    return lines;
  }

  lines.push("| WI | Backlog | Title | Status | Category |");
  lines.push("|----|---------|-------|--------|----------|");
  for (const r of rows) {
    lines.push(
      `| ${r.wi} | ${r.id} | ${r.title} | ${r.status} | ${r.category} |`
    );
  }
  lines.push("");
  return lines;
}

function renderByCategorySections(items) {
  const lines = [];
  for (const cat of CATEGORIES) {
    const catItems = items.filter((i) => i.category === cat);
    lines.push(`## ${cat}`, "");
    if (catItems.length === 0) {
      lines.push("No items.", "");
      continue;
    }
    lines.push(
      "| ID | Title | Status | Priority | Effort | Tags | Design Doc |"
    );
    lines.push(
      "|----|-------|--------|----------|--------|------|------------|"
    );
    for (const item of catItems) {
      const tags = (item.tags || []).join(", ");
      lines.push(
        `| ${item.id} | ${item.title} | ${item.status} | ${pad(item.priority)} | ${pad(item.effort)} | ${tags} | ${designDocCell(item.design_doc)} |`
      );
    }
    lines.push("");
  }
  return lines;
}

function renderTagsIndex(items) {
  const lines = ["## Tags Index", ""];
  const tagMap = {};
  for (const item of items) {
    for (const tag of item.tags || []) {
      if (!tagMap[tag]) tagMap[tag] = [];
      tagMap[tag].push(item.id);
    }
  }
  const sorted = Object.entries(tagMap).sort(
    (a, b) => b[1].length - a[1].length
  );

  if (sorted.length === 0) {
    lines.push("No tags.", "");
    return lines;
  }

  lines.push("| Tag | Count | Items |");
  lines.push("|-----|------:|-------|");
  for (const [tag, ids] of sorted) {
    lines.push(`| ${tag} | ${ids.length} | ${ids.join(", ")} |`);
  }
  lines.push("");
  return lines;
}

function renderRecentlyUpdated(items) {
  const lines = ["## Recently Updated", ""];
  const now = new Date();
  const recent = items
    .filter((i) => i.updated && daysFromNow(i.updated, now) >= -7)
    .sort((a, b) => new Date(b.updated) - new Date(a.updated))
    .slice(0, 10);

  if (recent.length === 0) {
    lines.push("No items updated in the last 7 days.", "");
    return lines;
  }

  lines.push("| ID | Title | Updated | Change |");
  lines.push("|----|-------|---------|--------|");
  for (const item of recent) {
    const note = truncate(latestNote(item), 60);
    lines.push(`| ${item.id} | ${item.title} | ${item.updated} | ${note} |`);
  }
  lines.push("");
  return lines;
}

function renderFooter(archivedCount) {
  return [
    "---",
    "",
    `> ${archivedCount} items archived. See \`archive.yaml\` for history.`,
    ""
  ];
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main() {
  let backlogData, archiveData;

  try {
    backlogData = loadYaml(BACKLOG_PATH);
  } catch (err) {
    console.error(`Error reading backlog.yaml: ${err.message}`);
    process.exit(1);
  }

  try {
    archiveData = loadYaml(ARCHIVE_PATH);
  } catch (err) {
    console.error(`Error reading archive.yaml: ${err.message}`);
    process.exit(1);
  }

  const items = (backlogData && backlogData.items) || [];
  const archived = (archiveData && archiveData.items) || [];
  const archivedCount = archived.length;

  const sections = [
    ...renderHeader(),
    ...renderExecutiveSummary(items),
    ...renderSummaryTable(items, archivedCount),
    ...renderCategoryMatrix(items),
    ...renderPriorityBoard(items),
    ...renderWiCrossReference(items),
    ...renderByCategorySections(items),
    ...renderTagsIndex(items),
    ...renderRecentlyUpdated(items),
    ...renderFooter(archivedCount)
  ];

  const output = sections.join("\n");
  fs.writeFileSync(OUTPUT_PATH, output, "utf8");
  console.log(
    `Rendered ${path.relative(REPO_ROOT, OUTPUT_PATH)} — ${items.length} active items, ${archivedCount} archived.`
  );
}

main();
