// Generated by claude-sf-toolkit. Customize for your project.
#!/usr/bin/env node
"use strict";

/**
 * drift-compare.js — Map org metadata to local source and classify drift
 *
 * Takes org query JSON (from `sf data query --json` or piped from MCP) and
 * compares each component against the local git source to classify as:
 *   IN_SYNC, CANDIDATE, ORG_ONLY, or LOCAL_ONLY
 *
 * Usage:
 *   node scripts/drift-compare.js --input /tmp/org-flows.json --type flows [options]
 *   sf data query --query "..." --json | node scripts/drift-compare.js --type flows
 *
 * Options:
 *   --input <path>          JSON file with org query results (omit to read stdin)
 *   --type <type>           Metadata type: flows | objects (required)
 *   --since <date|Nd>       Only include drift after this date (default: 30d)
 *   --source-dir <path>     Source directory (default: force-app/main/default)
 *   --metadata-path <path>  Alias for --source-dir
 *   --json                  JSON output (default: markdown table)
 *   --summary               Summary counts only (no per-component detail)
 *   --help                  Show this help message
 *
 * Input JSON format (sf data query --json):
 *   { "status": 0, "result": { "records": [...] } }
 *
 * Also accepts bare array of records: [{ "DeveloperName": "...", ... }]
 *
 * Exit codes: 0 = success (no drift or drift found), 1 = error, 2 = file error
 */

const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");

const REPO_ROOT = path.join(__dirname, "..");

// ---------------------------------------------------------------------------
// Argument parsing
// ---------------------------------------------------------------------------

function parseArgs(argv) {
  const args = {};
  let i = 2;
  while (i < argv.length) {
    const key = argv[i];
    if (key === "--help") {
      console.log(
        [
          "Usage: node scripts/drift-compare.js --type flows [options]",
          "",
          "Options:",
          "  --input <path>          JSON file with org query results (omit to read stdin)",
          "  --type <type>           Metadata type: flows | objects (required)",
          "  --since <date|Nd>       Only include drift after this date (default: 30d)",
          "  --source-dir <path>     Source directory (default: force-app/main/default)",
          "  --metadata-path <path>  Alias for --source-dir",
          "  --json                  JSON output (default: markdown table)",
          "  --summary               Summary counts only (no per-component detail)",
          "  --help                  Show this help message"
        ].join("\n")
      );
      process.exit(0);
    }
    if (key.startsWith("--")) {
      const name = key.slice(2);
      if (name === "json" || name === "summary") {
        args[name] = true;
        i++;
      } else {
        if (i + 1 >= argv.length) {
          console.error(`Error: --${name} requires a value`);
          process.exit(1);
        }
        args[name] = argv[i + 1];
        i += 2;
      }
    } else {
      console.error(`Error: unexpected argument "${key}"`);
      process.exit(1);
    }
  }
  return args;
}

// ---------------------------------------------------------------------------
// Date helpers
// ---------------------------------------------------------------------------

function parseSinceDate(since) {
  if (!since) {
    // Default: 30 days ago
    const d = new Date();
    d.setDate(d.getDate() - 30);
    return d;
  }
  // Relative: "7d", "30d", "90d"
  const relMatch = since.match(/^(\d+)d$/);
  if (relMatch) {
    const d = new Date();
    d.setDate(d.getDate() - parseInt(relMatch[1], 10));
    return d;
  }
  // Absolute: "2026-03-01"
  const d = new Date(since + "T00:00:00Z");
  if (isNaN(d.getTime())) {
    console.error(
      `Error: invalid --since date "${since}". Use YYYY-MM-DD or Nd (e.g., 30d)`
    );
    process.exit(1);
  }
  return d;
}

function formatDate(d) {
  if (!d) return "n/a";
  if (typeof d === "string") d = new Date(d);
  return d.toISOString().slice(0, 10);
}

function daysBetween(a, b) {
  const msPerDay = 86400000;
  return Math.round(Math.abs((new Date(a) - new Date(b)) / msPerDay));
}

// ---------------------------------------------------------------------------
// Git date lookup
// ---------------------------------------------------------------------------

function getGitDate(filePath) {
  const absPath = path.resolve(REPO_ROOT, filePath);
  if (!fs.existsSync(absPath)) return null;

  try {
    const dateStr = execSync(`git log -1 --format="%aI" -- "${filePath}"`, {
      encoding: "utf8",
      cwd: REPO_ROOT,
      stdio: ["pipe", "pipe", "pipe"]
    }).trim();
    if (dateStr) return new Date(dateStr);
  } catch {
    // Not in git — fall back to filesystem mtime
  }

  try {
    const stat = fs.statSync(absPath);
    return stat.mtime;
  } catch {
    return null;
  }
}

// ---------------------------------------------------------------------------
// Local source scanning
// ---------------------------------------------------------------------------

function getLocalFlows(sourceDir) {
  const flowDir = path.join(REPO_ROOT, sourceDir, "flows");
  if (!fs.existsSync(flowDir)) return new Set();
  return new Set(
    fs
      .readdirSync(flowDir)
      .filter((f) => f.endsWith(".flow-meta.xml"))
      .map((f) => f.replace(".flow-meta.xml", ""))
  );
}

function getLocalObjects(sourceDir) {
  const objDir = path.join(REPO_ROOT, sourceDir, "objects");
  if (!fs.existsSync(objDir)) return new Set();
  return new Set(
    fs.readdirSync(objDir).filter((f) => {
      const full = path.join(objDir, f);
      return fs.statSync(full).isDirectory();
    })
  );
}

// ---------------------------------------------------------------------------
// Mapping functions: org record -> local file path
// ---------------------------------------------------------------------------

function mapFlowToLocal(record, sourceDir) {
  const devName = record.DeveloperName || record.ApiName || record.FullName;
  if (!devName) return null;
  return path.join(sourceDir, "flows", `${devName}.flow-meta.xml`);
}

function mapObjectToLocal(record, sourceDir) {
  const devName = record.DeveloperName || record.FullName;
  if (!devName) return null;
  if (record.TableEnumOrId) {
    return path.join(
      sourceDir,
      "objects",
      record.TableEnumOrId,
      "fields",
      `${devName}.field-meta.xml`
    );
  }
  return path.join(sourceDir, "objects", devName);
}

// ---------------------------------------------------------------------------
// Core comparison
// ---------------------------------------------------------------------------

/**
 * Compare org records against local source.
 * Returns an array of classification objects.
 */
function compareRecords(records, type, sourceDir, sinceDate) {
  const mapFn = type === "flows" ? mapFlowToLocal : mapObjectToLocal;
  const localSet =
    type === "flows" ? getLocalFlows(sourceDir) : getLocalObjects(sourceDir);
  const results = [];
  const orgNames = new Set();

  for (const record of records) {
    const devName = record.DeveloperName || record.ApiName || record.FullName;
    if (!devName) continue;

    orgNames.add(devName);
    const localPath = mapFn(record, sourceDir);
    if (!localPath) continue;

    const orgDate = record.LastModifiedDate
      ? new Date(record.LastModifiedDate)
      : null;
    const orgModifiedBy = record.LastModifiedBy
      ? typeof record.LastModifiedBy === "object"
        ? record.LastModifiedBy.Name
        : record.LastModifiedBy
      : "Unknown";

    const absPath = path.resolve(REPO_ROOT, localPath);
    const localExists = fs.existsSync(absPath);

    if (!localExists) {
      results.push({
        name: devName,
        type: type === "flows" ? "Flow" : "Object/Field",
        classification: "ORG_ONLY",
        org_date: orgDate ? orgDate.toISOString() : null,
        org_modified_by: orgModifiedBy,
        git_date: null,
        gap_days: null,
        local_path: localPath,
        reason: "Exists in org but not in local source"
      });
      continue;
    }

    const gitDate = getGitDate(localPath);

    if (!orgDate) {
      results.push({
        name: devName,
        type: type === "flows" ? "Flow" : "Object/Field",
        classification: "UNKNOWN",
        org_date: null,
        org_modified_by: orgModifiedBy,
        git_date: gitDate ? gitDate.toISOString() : null,
        gap_days: null,
        local_path: localPath,
        reason: "No LastModifiedDate available from org"
      });
      continue;
    }

    if (sinceDate && orgDate < sinceDate) {
      continue;
    }

    if (gitDate && orgDate > gitDate) {
      const gap = daysBetween(orgDate, gitDate);
      results.push({
        name: devName,
        type: type === "flows" ? "Flow" : "Object/Field",
        classification: "CANDIDATE",
        org_date: orgDate.toISOString(),
        org_modified_by: orgModifiedBy,
        git_date: gitDate.toISOString(),
        gap_days: gap,
        local_path: localPath,
        reason: `Org is ${gap} day(s) newer than local source`
      });
    } else {
      results.push({
        name: devName,
        type: type === "flows" ? "Flow" : "Object/Field",
        classification: "IN_SYNC",
        org_date: orgDate.toISOString(),
        org_modified_by: orgModifiedBy,
        git_date: gitDate ? gitDate.toISOString() : null,
        gap_days: 0,
        local_path: localPath,
        reason: "Local source is current or newer"
      });
    }
  }

  // Check for LOCAL_ONLY
  for (const localName of localSet) {
    if (!orgNames.has(localName)) {
      const localPath = mapFn({ DeveloperName: localName }, sourceDir);
      if (!localPath) continue;
      const gitDate = getGitDate(localPath);
      results.push({
        name: localName,
        type: type === "flows" ? "Flow" : "Object/Field",
        classification: "LOCAL_ONLY",
        org_date: null,
        org_modified_by: null,
        git_date: gitDate ? gitDate.toISOString() : null,
        gap_days: null,
        local_path: localPath,
        reason: "Exists in local source but not active in org"
      });
    }
  }

  return results;
}

// ---------------------------------------------------------------------------
// Output formatters
// ---------------------------------------------------------------------------

function formatSummary(results) {
  const counts = {
    CANDIDATE: 0,
    ORG_ONLY: 0,
    LOCAL_ONLY: 0,
    IN_SYNC: 0,
    UNKNOWN: 0
  };
  for (const r of results) {
    counts[r.classification] = (counts[r.classification] || 0) + 1;
  }
  return counts;
}

function formatTable(results) {
  const lines = [];
  const drifted = results.filter((r) => r.classification === "CANDIDATE");
  const orgOnly = results.filter((r) => r.classification === "ORG_ONLY");
  const localOnly = results.filter((r) => r.classification === "LOCAL_ONLY");
  const counts = formatSummary(results);

  lines.push("### Drift Comparison Summary");
  lines.push("");
  lines.push(`- Components scanned: ${results.length}`);
  lines.push(`- Drift candidates (org newer): ${counts.CANDIDATE}`);
  lines.push(`- Org-only (not in source): ${counts.ORG_ONLY}`);
  lines.push(`- Local-only (not in org): ${counts.LOCAL_ONLY}`);
  lines.push(`- In sync: ${counts.IN_SYNC}`);
  lines.push("");

  if (drifted.length > 0) {
    lines.push("### Drift Candidates (org date newer than local)");
    lines.push("");
    lines.push(
      "| # | Component | Type | Org Modified | Modified By | Git Date | Gap |"
    );
    lines.push("| --- | --- | --- | --- | --- | --- | --- |");
    drifted
      .sort((a, b) => (b.gap_days || 0) - (a.gap_days || 0))
      .forEach((r, i) => {
        lines.push(
          `| ${i + 1} | ${r.name} | ${r.type} | ${formatDate(r.org_date)} | ${r.org_modified_by} | ${formatDate(r.git_date)} | ${r.gap_days}d |`
        );
      });
    lines.push("");
  }

  if (orgOnly.length > 0) {
    lines.push("### Org-Only (not in source control)");
    lines.push("");
    lines.push("| # | Component | Type | Org Modified | Modified By |");
    lines.push("| --- | --- | --- | --- | --- |");
    orgOnly.forEach((r, i) => {
      lines.push(
        `| ${i + 1} | ${r.name} | ${r.type} | ${formatDate(r.org_date)} | ${r.org_modified_by} |`
      );
    });
    lines.push("");
  }

  if (localOnly.length > 0 && localOnly.length <= 20) {
    lines.push("### Local-Only (in source, not active in org)");
    lines.push("");
    lines.push("| # | Component | Type | Git Date |");
    lines.push("| --- | --- | --- | --- |");
    localOnly.forEach((r, i) => {
      lines.push(
        `| ${i + 1} | ${r.name} | ${r.type} | ${formatDate(r.git_date)} |`
      );
    });
    lines.push("");
  } else if (localOnly.length > 20) {
    lines.push(
      `### Local-Only: ${localOnly.length} components (in source, not active in org) — list omitted (>20)`
    );
    lines.push("");
  }

  if (counts.CANDIDATE === 0 && counts.ORG_ONLY === 0) {
    lines.push("**No drift detected.** Local source matches the org.");
  }

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Input parsing
// ---------------------------------------------------------------------------

function extractRecords(raw) {
  let data;
  try {
    data = JSON.parse(raw);
  } catch (err) {
    console.error(`Error: invalid JSON input — ${err.message}`);
    process.exit(2);
  }

  // sf data query --json format: { status: 0, result: { records: [...] } }
  if (data.result && Array.isArray(data.result.records)) {
    return data.result.records;
  }
  // MCP query_records format: { records: [...] }
  if (data.records && Array.isArray(data.records)) {
    return data.records;
  }
  // Bare array
  if (Array.isArray(data)) {
    return data;
  }
  // Single result wrapper
  if (data.result && Array.isArray(data.result)) {
    return data.result;
  }

  console.error(
    "Error: cannot find records array in input JSON. Expected sf data query --json format, MCP format, or bare array."
  );
  process.exit(2);
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main() {
  const args = parseArgs(process.argv);

  if (!args.type) {
    console.error("Error: --type is required (flows | objects)");
    process.exit(1);
  }
  if (!["flows", "objects"].includes(args.type)) {
    console.error(
      `Error: invalid --type "${args.type}". Must be flows or objects.`
    );
    process.exit(1);
  }

  // Support both --source-dir and --metadata-path
  const sourceDir = args["source-dir"] || args["metadata-path"] || "force-app/main/default";
  const sinceDate = parseSinceDate(args.since);

  // Read input
  let raw;
  if (args.input) {
    const inputPath = path.resolve(REPO_ROOT, args.input);
    if (!fs.existsSync(inputPath)) {
      console.error(`Error: input file not found: ${inputPath}`);
      process.exit(2);
    }
    raw = fs.readFileSync(inputPath, "utf8");
  } else {
    // Read from stdin
    try {
      raw = fs.readFileSync(0, "utf8");
    } catch {
      console.error(
        "Error: no --input file and no stdin data. Pipe org query JSON or use --input."
      );
      process.exit(1);
    }
  }

  const records = extractRecords(raw);
  console.error(
    `Processing ${records.length} org records (type: ${args.type}, since: ${formatDate(sinceDate)})...`
  );

  // Run comparison
  const results = compareRecords(records, args.type, sourceDir, sinceDate);
  const counts = formatSummary(results);

  // Output
  if (args.json) {
    const output = {
      type: args.type,
      since: formatDate(sinceDate),
      source_dir: sourceDir,
      total_scanned: results.length,
      counts,
      candidates: results.filter((r) => r.classification === "CANDIDATE"),
      org_only: results.filter((r) => r.classification === "ORG_ONLY"),
      local_only: results.filter((r) => r.classification === "LOCAL_ONLY")
    };
    if (!args.summary) {
      output.all_results = results;
    }
    console.log(JSON.stringify(output, null, 2));
  } else if (args.summary) {
    console.log(
      `Drift candidates: ${counts.CANDIDATE} | Org-only: ${counts.ORG_ONLY} | Local-only: ${counts.LOCAL_ONLY} | In sync: ${counts.IN_SYNC}`
    );
  } else {
    console.log(formatTable(results));
  }

  process.exit(0);
}

main();
