// Generated by claude-sf-toolkit. Customize for your project.
/**
 * flow-index.js — Parse, filter, and categorize Salesforce flows from repo XML metadata.
 *
 * Scans flow XML files, extracts metadata (process type, status, trigger type, etc.),
 * applies optional filters, and categorizes flows using a configurable categories file.
 *
 * Usage:
 *   node scripts/flow-index.js                                  # All active flows as JSON
 *   node scripts/flow-index.js --category billing               # Filter to one category
 *   node scripts/flow-index.js --include-inactive               # Include inactive flows
 *   node scripts/flow-index.js --no-filter                      # Skip all filters (raw list)
 *   node scripts/flow-index.js --table                          # Markdown table output
 *   node scripts/flow-index.js --record-triggered               # Only record-triggered flows
 *   node scripts/flow-index.js --stats                          # Summary stats only
 *   node scripts/flow-index.js --metadata-path src/main/default # Custom metadata path
 *   node scripts/flow-index.js --categories-path config/cats.js # Custom categories module
 *
 * Options:
 *   --metadata-path <path>      Path to SFDX metadata directory (default: force-app/main/default)
 *   --categories-path <path>    Path to flow categories JS module (default: docs/flows/flow-categories.json)
 *                               Accepts JSON (category→flow-name-array map) or a JS module exporting
 *                               a categorize(flowName) function.
 *   --filters-path <path>       Path to flow-filters.json (default: none — no filters applied)
 *   --category <name>           Filter to a single category
 *   --include-inactive          Include inactive flows (excluded by default)
 *   --no-filter                 Skip all filters (show raw list)
 *   --record-triggered          Only show record-triggered flows
 *   --table                     Output as markdown table
 *   --stats                     Output summary statistics only
 *   --json                      Force JSON output (default when no --table/--stats)
 *   --help                      Show this help message
 *
 * Exit codes:
 *   0 — Success
 *   1 — Error (missing paths, bad args)
 */

const fs = require("fs");
const path = require("path");

const REPO_ROOT = path.join(__dirname, "..");

// --- CLI argument parsing ---

const args = process.argv.slice(2);

if (args.includes("--help")) {
  const lines = [];
  lines.push("flow-index.js — Parse, filter, and categorize Salesforce flows from repo XML metadata");
  lines.push("");
  lines.push("Usage:");
  lines.push("  node scripts/flow-index.js [options]");
  lines.push("");
  lines.push("Options:");
  lines.push("  --metadata-path <path>      Path to SFDX metadata directory (default: force-app/main/default)");
  lines.push("  --categories-path <path>    Path to flow categories file (default: docs/flows/flow-categories.json)");
  lines.push("                              JSON: { \"category_name\": [\"FlowName1\", ...] }");
  lines.push("                              JS module: exports a categorize(flowName) function");
  lines.push("  --filters-path <path>       Path to flow-filters.json (default: none — no filters)");
  lines.push("                              JSON: { \"skip_sunset\": { \"explicit\": [], \"patterns\": [] }, ... }");
  lines.push("  --category <name>           Filter to a single category");
  lines.push("  --include-inactive          Include inactive flows");
  lines.push("  --no-filter                 Skip all filters (raw list)");
  lines.push("  --record-triggered          Only record-triggered flows");
  lines.push("  --table                     Markdown table output");
  lines.push("  --stats                     Summary statistics only");
  lines.push("  --help                      Show this help message");
  lines.push("");
  lines.push("Filter file format (--filters-path):");
  lines.push("  {");
  lines.push('    "skip_sunset":  { "explicit": ["FlowName"], "patterns": ["Old_*"] },');
  lines.push('    "skip_onetime": { "explicit": [], "patterns": [] },');
  lines.push('    "skip_temp":    { "explicit": [], "patterns": [] },');
  lines.push('    "skip_platform": { "explicit": [] }');
  lines.push("  }");
  lines.push("");
  lines.push("Exit codes:");
  lines.push("  0 — Success");
  lines.push("  1 — Error");
  console.log(lines.join("\n"));
  process.exit(0);
}

const opts = {
  includeInactive: args.includes("--include-inactive"),
  noFilter: args.includes("--no-filter"),
  table: args.includes("--table"),
  recordTriggered: args.includes("--record-triggered"),
  stats: args.includes("--stats"),
  category: getArgValue(args, "--category")
};

const metadataPath = getArgValue(args, "--metadata-path") || "force-app/main/default";
const categoriesPath = getArgValue(args, "--categories-path") || "docs/flows/flow-categories.json";
const filtersPath = getArgValue(args, "--filters-path") || null;

const flowDir = path.join(REPO_ROOT, metadataPath, "flows");

// --- Load categorizer ---
const categorizeFn = loadCategorizer(path.join(REPO_ROOT, categoriesPath));

// --- Load filters (optional) ---
const filterSets = filtersPath ? loadFilters(path.join(REPO_ROOT, filtersPath)) : null;

// --- Main ---
if (!fs.existsSync(flowDir)) {
  console.error(`Error: Flow directory not found: ${flowDir}`);
  process.exit(1);
}

const allFlows = loadAllFlows();
const results = applyFilters(allFlows, opts);

if (opts.stats) {
  printStats(allFlows, results);
} else if (opts.table) {
  printTable(results);
} else {
  process.stdout.write(JSON.stringify(results, null, 2) + "\n");
}

// ============================================================
// Functions
// ============================================================

/**
 * Get the value following a named argument.
 */
function getArgValue(args, name) {
  const idx = args.indexOf(name);
  if (idx === -1 || idx + 1 >= args.length) return null;
  return args[idx + 1];
}

/**
 * Convert a glob-like pattern (e.g. "flow_*") to a RegExp.
 */
function patternToRegex(pattern) {
  const escaped = pattern
    .replace(/[.+^${}()|[\]\\]/g, "\\$&")
    .replace(/\*/g, ".*");
  return new RegExp("^" + escaped + "$");
}

/**
 * Extract a simple XML element value using regex.
 */
function xmlVal(xml, tag) {
  const re = new RegExp("<" + tag + ">([^<]*)</" + tag + ">");
  const m = xml.match(re);
  return m ? m[1] : null;
}

/**
 * Extract the value of an element inside the <start> block.
 */
function xmlStartVal(xml, tag) {
  const startMatch = xml.match(/<start>([\s\S]*?)<\/start>/);
  if (!startMatch) return null;
  const startBlock = startMatch[1];
  const re = new RegExp("<" + tag + ">([^<]*)</" + tag + ">");
  const m = startBlock.match(re);
  return m ? m[1] : null;
}

/**
 * Extract the top-level <description> element (direct child of <Flow>).
 */
function xmlTopDescription(xml) {
  const m = xml.match(/<description>([\s\S]*?)<\/description>/);
  return m ? m[1].trim() : null;
}

/**
 * Check if a flow name matches a managed package pattern (namespace__).
 */
function isManagedPackage(name) {
  return /^[a-zA-Z][a-zA-Z0-9_]*__\w/.test(name);
}

/**
 * Load a categorizer function from a JSON or JS file.
 *
 * JSON format: { "category_name": ["FlowName1", "FlowName2"] }
 * JS format: module.exports = function(flowName) { return "category"; }
 */
function loadCategorizer(filePath) {
  if (!fs.existsSync(filePath)) {
    // No categories file — return stub
    return function (_name) {
      return "uncategorized";
    };
  }

  if (filePath.endsWith(".json")) {
    const data = JSON.parse(fs.readFileSync(filePath, "utf8"));
    // Build a reverse map: flowName → category
    const flowToCategory = {};
    for (const [category, flowNames] of Object.entries(data)) {
      if (Array.isArray(flowNames)) {
        for (const name of flowNames) {
          flowToCategory[name] = category;
        }
      }
    }
    return function (name) {
      return flowToCategory[name] || "uncategorized";
    };
  }

  // JS module — must export a function
  try {
    const mod = require(filePath);
    if (typeof mod === "function") return mod;
    if (typeof mod.categorize === "function") return mod.categorize;
    if (typeof mod.cat === "function") return mod.cat;
    console.error(
      `Warning: ${filePath} does not export a categorize function. Using stub.`
    );
    return function (_name) {
      return "uncategorized";
    };
  } catch (e) {
    console.error(
      `Warning: Failed to load categorizer from ${filePath}: ${e.message}`
    );
    return function (_name) {
      return "uncategorized";
    };
  }
}

/**
 * Load filter sets from a JSON file.
 * Expected format matches flow-filters.json:
 *   { "skip_sunset": { "explicit": [], "patterns": [] }, ... }
 */
function loadFilters(filePath) {
  if (!fs.existsSync(filePath)) {
    console.error(`Warning: Filters file not found: ${filePath}. Skipping filters.`);
    return null;
  }

  try {
    const data = JSON.parse(fs.readFileSync(filePath, "utf8"));
    return {
      skipSunset: new Set(data.skip_sunset?.explicit || []),
      skipOnetime: new Set(data.skip_onetime?.explicit || []),
      skipTemp: new Set(data.skip_temp?.explicit || []),
      skipPlatform: new Set(data.skip_platform?.explicit || []),
      sunsetPatterns: (data.skip_sunset?.patterns || []).map(patternToRegex),
      onetimePatterns: (data.skip_onetime?.patterns || []).map(patternToRegex),
      tempPatterns: (data.skip_temp?.patterns || []).map(patternToRegex)
    };
  } catch (e) {
    console.error(`Warning: Failed to parse filters file: ${e.message}`);
    return null;
  }
}

/**
 * Determine filter status for a flow.
 */
function getFilterStatus(name, status, isTemplate) {
  if (isManagedPackage(name)) {
    return { filtered: true, filterReason: "managed_package" };
  }

  if (status !== "Active") {
    return { filtered: true, filterReason: "inactive" };
  }

  if (isTemplate) {
    return { filtered: true, filterReason: "template" };
  }

  // If no filter file loaded, only managed-package/inactive/template filters apply
  if (!filterSets) {
    return { filtered: false, filterReason: null };
  }

  if (
    filterSets.skipSunset.has(name) ||
    filterSets.sunsetPatterns.some((re) => re.test(name))
  ) {
    return { filtered: true, filterReason: "sunset" };
  }

  if (
    filterSets.skipOnetime.has(name) ||
    filterSets.onetimePatterns.some((re) => re.test(name))
  ) {
    return { filtered: true, filterReason: "onetime" };
  }

  if (
    filterSets.skipTemp.has(name) ||
    filterSets.tempPatterns.some((re) => re.test(name))
  ) {
    return { filtered: true, filterReason: "temp" };
  }

  if (filterSets.skipPlatform.has(name)) {
    return { filtered: true, filterReason: "platform" };
  }

  return { filtered: false, filterReason: null };
}

/**
 * Load and parse all flow XML files.
 */
function loadAllFlows() {
  const files = fs
    .readdirSync(flowDir)
    .filter((f) => f.endsWith(".flow-meta.xml"))
    .sort();
  const flows = [];

  for (const file of files) {
    const name = file.replace(".flow-meta.xml", "");
    const filePath = path.join(flowDir, file);
    const xml = fs.readFileSync(filePath, "utf8");

    const processType = xmlVal(xml, "processType") || "Unknown";
    const status = xmlVal(xml, "status") || "Unknown";
    const triggerType = xmlStartVal(xml, "triggerType") || null;
    const apiVersion = xmlVal(xml, "apiVersion") || null;
    const isTemplateStr = xmlVal(xml, "isTemplate");
    const isTemplate = isTemplateStr === "true";
    const description = xmlTopDescription(xml);
    const triggerObject = xmlStartVal(xml, "object") || null;

    const category = categorizeFn(name);
    const filterStatus = getFilterStatus(name, status, isTemplate);

    flows.push({
      name,
      category,
      processType,
      status,
      triggerType,
      triggerObject,
      apiVersion,
      isTemplate,
      hasDescription: description !== null && description.length > 0,
      filtered: filterStatus.filtered,
      filterReason: filterStatus.filterReason
    });
  }

  return flows;
}

/**
 * Apply CLI filters to the flow list.
 */
function applyFilters(flows, opts) {
  let result = flows;

  if (!opts.noFilter) {
    if (opts.includeInactive) {
      result = result.filter(
        (f) => !f.filtered || f.filterReason === "inactive"
      );
      result = result.map((f) => {
        if (f.filterReason === "inactive") {
          return Object.assign({}, f, { filtered: false, filterReason: null });
        }
        return f;
      });
    } else {
      result = result.filter((f) => !f.filtered);
    }
  }

  if (opts.recordTriggered) {
    result = result.filter(
      (f) =>
        f.triggerType === "RecordBeforeSave" ||
        f.triggerType === "RecordAfterSave" ||
        f.triggerType === "RecordBeforeDelete"
    );
  }

  if (opts.category) {
    result = result.filter((f) => f.category === opts.category);
  }

  return result;
}

/**
 * Print summary statistics.
 */
function printStats(allFlows, filteredResults) {
  const total = allFlows.length;
  const active = allFlows.filter((f) => f.status === "Active").length;
  const inactive = total - active;
  const filtered = allFlows.filter((f) => f.filtered).length;
  const remaining = allFlows.filter((f) => !f.filtered).length;

  const byCategory = {};
  for (const f of allFlows.filter((fl) => !fl.filtered)) {
    byCategory[f.category] = (byCategory[f.category] || 0) + 1;
  }

  const byProcessType = {};
  for (const f of allFlows) {
    byProcessType[f.processType] = (byProcessType[f.processType] || 0) + 1;
  }

  const byTriggerType = {};
  for (const f of allFlows) {
    if (f.triggerType) {
      byTriggerType[f.triggerType] = (byTriggerType[f.triggerType] || 0) + 1;
    }
  }

  const recordTriggered = allFlows.filter(
    (f) =>
      f.triggerType === "RecordBeforeSave" ||
      f.triggerType === "RecordAfterSave" ||
      f.triggerType === "RecordBeforeDelete"
  ).length;

  const withDescription = allFlows.filter((f) => f.hasDescription).length;
  const withoutDescription = total - withDescription;

  const stats = {
    total,
    active,
    inactive,
    filtered,
    remaining,
    by_category: sortObj(byCategory),
    by_process_type: sortObj(byProcessType),
    by_trigger_type: sortObj(byTriggerType),
    record_triggered: recordTriggered,
    with_description: withDescription,
    without_description: withoutDescription
  };

  process.stdout.write(JSON.stringify(stats, null, 2) + "\n");
}

/**
 * Print results as a markdown table.
 */
function printTable(flows) {
  const header =
    "| Name | Category | Process Type | Status | Trigger Type | Trigger Object | API Version | Description |";
  const sep =
    "|------|----------|-------------|--------|-------------|----------------|-------------|-------------|";
  const lines = [header, sep];

  for (const f of flows) {
    lines.push(
      "| " +
        [
          f.name,
          f.category,
          f.processType,
          f.status,
          f.triggerType || "",
          f.triggerObject || "",
          f.apiVersion || "",
          f.hasDescription ? "Yes" : "No"
        ].join(" | ") +
        " |"
    );
  }

  process.stdout.write(lines.join("\n") + "\n");
}

/**
 * Sort an object's keys by value (descending).
 */
function sortObj(obj) {
  const sorted = {};
  Object.entries(obj)
    .sort((a, b) => b[1] - a[1])
    .forEach(([k, v]) => {
      sorted[k] = v;
    });
  return sorted;
}
