#!/usr/bin/env node
// Generated by claude-sf-toolkit. Customize for your project.
"use strict";

/**
 * resolve-cache.js — Validate and return cached SF Toolkit resolver context
 *
 * Checks the .claude/sf-toolkit-cache.json file for validity:
 *   1. File exists and is parseable JSON
 *   2. Cache has not expired (based on _cache.expiresAt)
 *   3. Source file modification times match cached values
 *
 * Usage:
 *   node scripts/resolve-cache.js [options]
 *
 * Options:
 *   --cache-path <path>   Cache file path (default: .claude/sf-toolkit-cache.json)
 *   --check-mtimes        Also validate source file modification times (slower but thorough)
 *   --json                Always output JSON (default)
 *   --invalidate          Delete the cache file and exit
 *   --help                Show this help message
 *
 * Output (JSON):
 *   { "valid": true,  "ageHours": 2.3, "context": { ... } }
 *   { "valid": false, "reason": "Cache expired (25.1h old, expires at ...)" }
 *
 * Exit codes: 0 = cache valid, 1 = cache invalid/missing
 */

const fs = require("fs");
const path = require("path");

const REPO_ROOT = path.join(__dirname, "..");

// --- CLI argument parsing ---------------------------------------------------

const args = process.argv.slice(2);

if (args.includes("--help")) {
  const lines = fs.readFileSync(__filename, "utf8").split("\n");
  const start = lines.findIndex((l) => l.includes("* resolve-cache.js"));
  const end = lines.findIndex((l, i) => i > start && l.trim() === "*/");
  console.log(
    lines
      .slice(start, end)
      .map((l) => l.replace(/^\s*\*\s?/, ""))
      .join("\n")
  );
  process.exit(0);
}

function argVal(flag, fallback) {
  const i = args.indexOf(flag);
  return i !== -1 && args[i + 1] ? args[i + 1] : fallback;
}

const cachePath = path.resolve(
  REPO_ROOT,
  argVal("--cache-path", ".claude/sf-toolkit-cache.json")
);
const checkMtimes = args.includes("--check-mtimes");
const invalidate = args.includes("--invalidate");

// --- Helpers ----------------------------------------------------------------

function output(valid, detail) {
  console.log(JSON.stringify({ valid, ...detail }));
  process.exit(valid ? 0 : 1);
}

function getMtime(filePath) {
  try {
    return fs.statSync(filePath).mtime.toISOString();
  } catch {
    return null;
  }
}

// --- Invalidate mode --------------------------------------------------------

if (invalidate) {
  try {
    fs.unlinkSync(cachePath);
    output(false, { reason: "Cache invalidated (file deleted)" });
  } catch {
    output(false, { reason: "No cache file to invalidate" });
  }
}

// --- Read and parse cache ---------------------------------------------------

if (!fs.existsSync(cachePath)) {
  output(false, { reason: "Cache file not found" });
}

let cached;
try {
  cached = JSON.parse(fs.readFileSync(cachePath, "utf8"));
} catch (err) {
  output(false, { reason: `Cache file parse error: ${err.message}` });
}

if (!cached._cache || !cached._cache.expiresAt || !cached._cache.resolvedAt) {
  output(false, { reason: "Missing cache metadata (_cache.expiresAt or _cache.resolvedAt)" });
}

// --- Check expiry -----------------------------------------------------------

const now = new Date();
const expiresAt = new Date(cached._cache.expiresAt);
const resolvedAt = new Date(cached._cache.resolvedAt);
const ageHours = (now - resolvedAt) / (1000 * 60 * 60);

if (now > expiresAt) {
  output(false, {
    reason: `Cache expired (${ageHours.toFixed(1)}h old, expired at ${cached._cache.expiresAt})`,
    ageHours: parseFloat(ageHours.toFixed(1)),
  });
}

// --- Check source file mtimes (optional, thorough mode) ---------------------

if (checkMtimes && cached._cache.sourceFiles) {
  for (const [relPath, cachedMtime] of Object.entries(cached._cache.sourceFiles)) {
    const absPath = path.resolve(REPO_ROOT, relPath);
    const currentMtime = getMtime(absPath);

    if (cachedMtime === null && currentMtime === null) {
      // File was missing when cached and still missing — OK
      continue;
    }
    if (cachedMtime === null && currentMtime !== null) {
      output(false, {
        reason: `Source file created since cache: ${relPath}`,
        ageHours: parseFloat(ageHours.toFixed(1)),
      });
    }
    if (cachedMtime !== null && currentMtime === null) {
      output(false, {
        reason: `Source file removed since cache: ${relPath}`,
        ageHours: parseFloat(ageHours.toFixed(1)),
      });
    }
    if (currentMtime !== cachedMtime) {
      output(false, {
        reason: `Source file modified since cache: ${relPath}`,
        ageHours: parseFloat(ageHours.toFixed(1)),
      });
    }
  }
}

// --- Cache is valid — return context ----------------------------------------

const { _cache, ...context } = cached;
output(true, {
  ageHours: parseFloat(ageHours.toFixed(1)),
  expiresIn: `${((expiresAt - now) / (1000 * 60 * 60)).toFixed(1)}h`,
  context,
});
