#!/usr/bin/env node
// Generated by claude-sf-toolkit v1.0.0
// Creates standard directory structure and starter files for an SF Toolkit project

const fs = require("fs");
const path = require("path");

const DIRECTORIES = [
  "docs/backlog",
  "docs/flows",
  "docs/components",
  "docs/design",
  "docs/tooling-reviews",
  "docs/release-reviews",
  "docs/platform-reviews",
  "docs/validation",
  "config",
  "scripts",
  ".claude/memory",
  ".claude/agents"
];

function scaffold(projectRoot, options = {}) {
  const created = [];
  const skipped = [];

  // Create directories
  for (const dir of DIRECTORIES) {
    // Skip backlog dir if backend is salesforce
    if (dir === "docs/backlog" && options.backlogBackend === "salesforce") {
      skipped.push(dir);
      continue;
    }

    const fullPath = path.join(projectRoot, dir);
    if (!fs.existsSync(fullPath)) {
      fs.mkdirSync(fullPath, { recursive: true });
      created.push(dir);
    } else {
      skipped.push(dir);
    }
  }

  return { created, skipped };
}

// CLI usage
if (require.main === module) {
  const projectRoot = process.argv[2] || process.cwd();
  const backlogBackend = process.argv[3] || "yaml";

  console.log(`Scaffolding SF Toolkit directories in: ${projectRoot}`);
  const result = scaffold(projectRoot, { backlogBackend });

  if (result.created.length > 0) {
    console.log(`\nCreated ${result.created.length} directories:`);
    result.created.forEach((d) => console.log(`  + ${d}`));
  }

  if (result.skipped.length > 0) {
    console.log(`\nSkipped ${result.skipped.length} (already exist):`);
    result.skipped.forEach((d) => console.log(`  - ${d}`));
  }
}

module.exports = { scaffold, DIRECTORIES };
